const vocabData = {
"Starter-A": [
{w: "A.m.", p: "Abrr.", t: "午前", s: "I wake up at 7 A.m."},
{w: "a(an)", p: "art.", t: "一個", s: "This is a book."},
{w: "above", p: "prep.", t: "在 ...上方", s: "The plane is above the clouds."},
{w: "afternoon", p: "n.", t: "下午", s: "Good afternoon, teacher."},
{w: "age", p: "n.", t: "年齡", s: "What is your age?"},
{w: "air", p: "n.", t: "空氣", s: "We need fresh air."},
{w: "airport", p: "n.", t: "飛機場", s: "We go to the airport."},
{w: "along", p: "prep.", t: "沿著", s: "Walk along the river."},
{w: "April", p: "n.", t: "四月", s: "My birthday is in April."},
{w: "around", p: "adv.", t: "圍繞 四周", s: "The children ran around."},
{w: "art", p: "v.", t: "藝術", s: "I like art class."},
{w: "at", p: "prep.", t: "在(時間)", s: "See you at ten o'clock."},
{w: "August", p: "n.", t: "八月", s: "August is very hot."},
{w: "aunt", p: "n.", t: "姑姑 嬸嬸 阿姨", s: "My aunt is a doctor."},
{w: "autumn(fall)", p: "n.", t: "秋天", s: "Leaves fall in autumn."},
{w: "baby", p: "n.", t: "嬰兒", s: "The baby is crying."},
{w: "back", p: "adv.", t: "回來", s: "When will you come back?"},
{w: "bad", p: "adj.", t: "壞的", s: "Eating too much candy is bad."},
{w: "balloon", p: "n.", t: "汽球", s: "The red balloon is big."},
{w: "behind", p: "prep.", t: "在~之後", s: "The cat is behind the door."},
{w: "below", p: "prep.", t: "在~之下", s: "The sun is below the sea."},
{w: "beside", p: "prep.", t: "在~旁邊", s: "Sit beside me."},
{w: "between", p: "prep.", t: "在~中間", s: "It is between A and B."},
{w: "big", p: "adj.", t: "大的", s: "The elephant is very big."},
{w: "bike", p: "n.", t: "腳踏車", s: "I ride my bike to school."},
{w: "black", p: "adj.", t: "黑色", s: "My dog is black."},
{w: "blackboard", p: "n.", t: "黑板", s: "Look at the blackboard."},
{w: "blind", p: "adj.", t: "失明的", s: "The blind man has a dog."},
{w: "blue", p: "n.;adj.", t: "藍色;憂鬱的", s: "The sky is blue today."},
{w: "boat", p: "n.", t: "船", s: "The boat is on the lake."},
{w: "book", p: "n.", t: "書", s: "I like reading this book."},
{w: "born", p: "v.", t: "出生", s: "I was born in Taiwan."},
{w: "boss", p: "n.", t: "老闆", s: "My boss is very kind."},
{w: "box", p: "n.", t: "箱子", s: "What's in the box?"},
{w: "boy", p: "n.", t: "男孩", s: "The boy is playing soccer."},
{w: "brother", p: "n.", t: "兄弟", s: "I have one brother."},
{w: "brown", p: "adj.", t: "棕色的", s: "The bear is brown."},
{w: "brush", p: "v.", t: "刷", s: "Brush your teeth every day."},
{w: "bus", p: "n.", t: "公車", s: "Go to school by bus."},
{w: "businessman", p: "n.", t: "生意人", s: "His father is a businessman."},
{w: "can(could)", p: "modal v.", t: "能夠", s: "I can swim very fast."},
{w: "car", p: "n.", t: "車子", s: "My dad has a new car."},
{w: "chalk", p: "n.", t: "粉筆", s: "Use chalk to write."},
{w: "cheap", p: "adj.", t: "便宜的", s: "The pen is very cheap."},
{w: "child", p: "n.", t: "孩子", s: "Every child likes toys."},
{w: "Chinese", p: "adj.", t: "中國的", s: "I like Chinese food."},
{w: "circle", p: "n. v.", t: "圓圈", s: "Draw a big circle."},
{w: "class", p: "n.", t: "班，課", s: "We are in the same class."},
{w: "classroom", p: "n.", t: "教室", s: "Our classroom is clean."},
{w: "clear", p: "adj.", t: "乾淨的", s: "The water is very clear."},
{w: "cloud", p: "n.", t: "雲", s: "There are clouds in the sky."},
{w: "cloudy", p: "adj.", t: "多雲的", s: "It is a cloudy day."},
{w: "coffee", p: "n.", t: "咖啡", s: "Mom drinks coffee every morning."},
{w: "cool", p: "adj. v.", t: "涼快的；酷的", s: "The weather is cool today."},
{w: "count", p: "v.", t: "數", s: "Count from one to ten."},
{w: "daughter", p: "n.", t: "女兒", s: "She is a good daughter."},
{w: "day", p: "n.", t: "日子", s: "Have a nice day."},
{w: "dead", p: "adj.", t: "死亡的", s: "The plant is dead."},
{w: "December", p: "n.", t: "十二月", s: "Christmas is in December."},
{w: "dictionary", p: "n.", t: "字典", s: "Look it up in the dictionary."},
{w: "doctor (Dr.)", p: "n.", t: "醫生", s: "The doctor helps sick people."},
{w: "drive", p: "v.", t: "開車", s: "My father drives to work."},
{w: "driver", p: "n.", t: "司機", s: "He is a bus driver."},
{w: "dry", p: "adj.", t: "乾的", s: "The clothes are dry."},
{w: "east", p: "n.", t: "東方", s: "The sun rises in the east."},
{w: "eight", p: "n.", t: "八", s: "I am eight years old."},
{w: "eighteen", p: "n.", t: "十八", s: "There are eighteen students."},
{w: "eighth", p: "n.", t: "第八", s: "He is the eighth student."},
{w: "eighty", p: "n.", t: "八十", s: "My grandpa is eighty."},
{w: "eleven", p: "n.", t: "十一", s: "It is eleven o'clock."},
{w: "English", p: "n.", t: "英文", s: "English is fun to learn."},
{w: "eraser", p: "n.", t: "橡皮擦", s: "May I borrow your eraser?"},
{w: "evening", p: "n.", t: "傍晚", s: "Good evening, everyone."},
{w: "excellent", p: "adj.", t: "優秀的", s: "Your work is excellent."},
{w: "exercise", p: "v.", t: "運動", s: "I exercise every morning."},
{w: "expensive", p: "adj.", t: "昂貴的", s: "The watch is too expensive."},
{w: "family", p: "n.", t: "家庭;家人", s: "I love my family."},
{w: "farm", p: "n.", t: "農場", s: "The farm has many cows."},
{w: "farmer", p: "n.", t: "農夫", s: "The farmer is busy."},
{w: "father(dad, daddy)", p: "n.", t: "爸爸", s: "My father is a teacher."},
{w: "February", p: "n.", t: "二月", s: "February is the second month."},
{w: "few", p: "pron.", t: "少數的", s: "I have a few friends."},
{w: "fifteen", p: "n.", t: "十五", s: "Fifteen minutes later."},
{w: "fifth", p: "n.", t: "第五", s: "May is the fifth month."},
{w: "fifty", p: "n.", t: "五十", s: "It costs fifty dollars."},
{w: "fine", p: "adj.", t: "很好", s: "I am fine, thank you."},
{w: "fire", p: "n.", t: "火", s: "Don't play with fire."},
{w: "first", p: "adv.", t: "第一 首先", s: "First, wash your hands."},
{w: "fisherman", p: "n.", t: "漁夫", s: "The fisherman is on the boat."},
{w: "five", p: "n.", t: "五", s: "I have five pens."},
{w: "forty", p: "n.", t: "四十", s: "My mother is forty."},
{w: "four", p: "n.", t: "四", s: "There are four chairs."},
{w: "fourteen", p: "n.", t: "十四", s: "Fourteen days make two weeks."},
{w: "fourth", p: "n.", t: "第四", s: "He is the fourth one."},
{w: "fresh", p: "adj.", t: "新鮮的", s: "The fruit is very fresh."},
{w: "Friday", p: "n.", t: "星期五", s: "We have a test on Friday."},
{w: "front", p: "n.", t: "前面", s: "In front of the house."},
{w: "future", p: "n.", t: "未來", s: "Think about your future."},
{w: "girl", p: "n.", t: "女孩", s: "The girl is very cute."},
{w: "good", p: "adj.", t: "好的", s: "Have a good day."},
{w: "grandfather", p: "n.", t: "祖父", s: "My grandfather is seventy."},
{w: "grandmother", p: "n.", t: "祖母", s: "My grandmother is kind."},
{w: "gray", p: "adj.", t: "灰色", s: "The sky is gray today."},
{w: "green", p: "adj.", t: "綠色", s: "The grass is green."},
{w: "half", p: "n.", t: "一半", s: "Half of the apple."},
{w: "hard", p: "adj.", t: "困難的", s: "The question is very hard."},
{w: "heavy", p: "adj.", t: "重的", s: "The box is too heavy."},
{w: "history", p: "n.", t: "歷史", s: "I like history class."},
{w: "homework", p: "n.", t: "回家作業", s: "Finish your homework."},
{w: "hour", p: "n.", t: "小時", s: "Wait for one hour."},
{w: "hundred", p: "n.", t: "百", s: "One hundred dollars."},
{w: "husband", p: "n.", t: "丈夫", s: "Her husband is a doctor."},
{w: "ice", p: "n.", t: "冰", s: "Put some ice in the juice."},
{w: "in", p: "prep.", t: "在~裡面", s: "The pen is in the box."},
{w: "into", p: "n.", t: "進入", s: "Go into the classroom."},
{w: "January", p: "n.", t: "一月", s: "January is cold."},
{w: "July", p: "n.", t: "七月", s: "July is summer."},
{w: "June", p: "n.", t: "六月", s: "School ends in June."},
{w: "kilogram", p: "n.", t: "公斤", s: "I weigh fifty kilograms."},
{w: "left", p: "adv.", t: "向左;左邊", s: "Turn left at the corner."},
{w: "light", p: "n. v.", t: "光線/點亮", s: "Turn on the light."},
{w: "little", p: "adj.", t: "一點", s: "Give me a little water."},
{w: "long", p: "adj.", t: "長的;久的", s: "A long time ago."},
{w: "many", p: "adj.", t: "許多的", s: "I have many friends."},
{w: "March", p: "n.", t: "三月", s: "March is the third month."},
{w: "May", p: "n.", t: "五月", s: "May Day is coming."},
{w: "may(might)", p: "modal v.", t: "可能", s: "It may rain tomorrow."},
{w: "million", p: "n.", t: "百萬", s: "One million people."},
{w: "minute", p: "n.", t: "分鐘", s: "Wait for ten minutes."},
{w: "Monday", p: "n.", t: "星期一", s: "I go to school on Monday."},
{w: "month", p: "n.", t: "月份", s: "Twelve months in a year."},
{w: "moon", p: "n.", t: "月亮", s: "The moon is round."},
{w: "morning", p: "n.", t: "早晨", s: "Good morning!"},
{w: "mother(mom)", p: "n.", t: "媽媽", s: "My mother is beautiful."},
{w: "mouth", p: "n.", t: "嘴", s: "Open your mouth."},
{w: "movie", p: "n.", t: "電影", s: "Let's watch a movie."},
{w: "much", p: "pron.", t: "多", s: "Thank you very much."},
{w: "music", p: "n.", t: "音樂", s: "Listen to the music."},
{w: "near", p: "prep.", t: "近", s: "The school is near my house."},
{w: "new", p: "adj.", t: "新的", s: "I have a new bag."},
{w: "night", p: "n.", t: "夜晚", s: "Good night, everyone."},
{w: "nine", p: "n.", t: "九", s: "I have nine balls."},
{w: "nineteen", p: "n.", t: "十九", s: "She is nineteen."},
{w: "ninety", p: "n.", t: "九十", s: "Ninety dollars."},
{w: "ninth", p: "n.", t: "第九", s: "September is the ninth month."},
{w: "noon", p: "n.", t: "中午", s: "We eat lunch at noon."},
{w: "north", p: "n.", t: "北方", s: "The birds fly north."},
{w: "notebook", p: "n.", t: "筆記本", s: "Write in your notebook."},
{w: "November", p: "n.", t: "十一月", s: "November is cold."},
{w: "now", p: "adv.", t: "現在", s: "Do it right now."},
{w: "o'clock", p: "n.", t: "點鐘", s: "It is six o'clock."},
{w: "October", p: "n.", t: "十月", s: "October is cool."},
{w: "OK", p: "adj.", t: "一切沒問題", s: "Everything is OK."},
{w: "old", p: "adj.", t: "老的", s: "My grandpa is old."},
{w: "on", p: "prep.", t: "在~上面", s: "The book is on the desk."},
{w: "one", p: "n.", t: "一", s: "Only one apple."},
{w: "orange", p: "adj.", t: "柳丁", s: "I want an orange juice."},
{w: "out", p: "adv.", t: "出去", s: "Go out and play."},
{w: "p.m.", p: "abbr.", t: "午後", s: "I come home at 5 p.m."},
{w: "paper", p: "n.", t: "紙", s: "A piece of paper."},
],
"Starter-B": [
{w: "pass", p: "v.", t: "通過，經過", s: "The bus just passed the park."},
{w: "past", p: "n.", t: "過去", s: "In the past, there were no cell phones."},
{w: "pen", p: "n.", t: "筆", s: "I write with a blue pen."},
{w: "pencil", p: "n.", t: "鉛筆", s: "Use a pencil to draw a circle."},
{w: "pink", p: "adj.", t: "粉紅色", s: "She likes her pink dress."},
{w: "place", p: "n.", t: "地方", s: "Taiwan is a beautiful place."},
{w: "playground", p: "n.", t: "運動場，遊戲場", s: "We play soccer on the playground."},
{w: "poor", p: "adj.", t: "貧窮的，可憐的", s: "The poor kitten is hungry."},
{w: "popcorn", p: "n.", t: "爆米花", s: "I like eating popcorn at the movies."},
{w: "pound", p: "n.", t: "磅", s: "I want two pounds of apples."},
{w: "pretty", p: "adj.", t: "漂亮的", s: "The flowers are very pretty."},
{w: "purple", p: "adj.", t: "紫色的", s: "Purple grapes are sweet."},
{w: "rain", p: "n. v.", t: "雨/下雨", s: "I like the sound of rain."},
{w: "rainbow", p: "n.", t: "彩虹", s: "See the rainbow in the sky!"},
{w: "rainy", p: "adj.", t: "下雨的", s: "Take an umbrella on rainy days."},
{w: "real", p: "adj.", t: "真實的", s: "Is that a real tiger?"},
{w: "red", p: "adj. n.", t: "紅色", s: "The apple is bright red."},
{w: "restroom", p: "n.", t: "洗手間", s: "Where is the restroom, please?"},
{w: "return", p: "v.", t: "回來", s: "When will you return home?"},
{w: "rich", p: "adj.", t: "富有的", s: "He is a very rich man."},
{w: "ride", p: "v.", t: "騎", s: "I can ride a bicycle."},
{w: "right", p: "adj. n.", t: "正確的;右邊", s: "Turn right at the bookstore."},
{w: "road", p: "n.", t: "道路", s: "The road is very long."},
{w: "rock", p: "n.", t: "岩石", s: "The big rock is by the river."},
{w: "ruler", p: "n.", t: "尺", s: "I use a ruler to draw lines."},
{w: "run", p: "v.", t: "跑", s: "The dog can run fast."},
{w: "sand", p: "n.", t: "沙子", s: "We play with sand on the beach."},
{w: "Saturday", p: "n.", t: "星期六", s: "Saturday is a holiday."},
{w: "say", p: "v.", t: "說", s: "Say hello to your teacher."},
{w: "school", p: "n.", t: "學校", s: "I go to school every morning."},
{w: "season", p: "n.", t: "季節", s: "Spring is a beautiful season."},
{w: "second", p: "adj. n.", t: "第二;秒", s: "He won the second prize."},
{w: "see", p: "v.", t: "看見", s: "I can see a bird in the tree."},
{w: "September", p: "n.", t: "九月", s: "September is the ninth month."},
{w: "seven", p: "n.", t: "七", s: "I have seven pencils."},
{w: "seventeen", p: "n.", t: "十七", s: "She is seventeen years old."},
{w: "seventh", p: "n. adj.", t: "第七", s: "It is his seventh birthday."},
{w: "seventy", p: "n.", t: "七十", s: "The book costs seventy dollars."},
{w: "ship", p: "n.", t: "船", s: "The ship is on the sea."},
{w: "short", p: "adj.", t: "短的", s: "The ruler is very short."},
{w: "sister", p: "n.", t: "姊妹", s: "My little sister is cute."},
{w: "sit", p: "v.", t: "坐", s: "Sit down on the chair."},
{w: "six", p: "n.", t: "六", s: "There are six eggs."},
{w: "sixteen", p: "n.", t: "十六", s: "Sixteen students are in class."},
{w: "sixth", p: "n. adj.", t: "第六", s: "He lives on the sixth floor."},
{w: "sixty", p: "n.", t: "六十", s: "My grandfather is sixty."},
{w: "ski", p: "v.", t: "滑雪", s: "We go to ski in winter."},
{w: "sky", p: "n.", t: "天空", s: "The sky is blue and clear."},
{w: "sleep", p: "v.", t: "睡覺", s: "I sleep at ten o'clock."},
{w: "small", p: "adj.", t: "小的", s: "The mouse is very small."},
{w: "snow", p: "v. n.", t: "下雪", s: "It does not snow in summer."},
{w: "son", p: "n.", t: "兒子", s: "He is a good son."},
{w: "south", p: "n. adj. adv.", t: "南方", s: "The birds fly south in winter."},
{w: "spell", p: "v.", t: "拼字", s: "How do you spell your name?"},
{w: "spring", p: "n.", t: "春天", s: "Flowers bloom in spring."},
{w: "square", p: "n.", t: "廣場;正方形", s: "The table is a square."},
{w: "star", p: "n.", t: "星星", s: "The stars are bright tonight."},
{w: "station", p: "n.", t: "車站", s: "The train is at the station."},
{w: "step", p: "n. v.", t: "步; 踐踏", s: "One step at a time."},
{w: "street", p: "n.", t: "街道", s: "Be careful crossing the street."},
{w: "strong", p: "adj.", t: "強壯的", s: "My father is very strong."},
{w: "student", p: "n.", t: "學生", s: "I am a junior high school student."},
{w: "summer", p: "n.", t: "夏天", s: "We like swimming in summer."},
{w: "Sunday", p: "n.", t: "星期日", s: "I play basketball on Sunday."},
{w: "sunny", p: "adj.", t: "晴天的", s: "It is a sunny day today."},
{w: "sweet", p: "adj.", t: "甜的;貼心的", s: "The candy is very sweet."},
{w: "swim", p: "v.", t: "游泳", s: "Can you swim in the sea?"},
{w: "take", p: "v.", t: "拿；帶", s: "Take your umbrella with you."},
{w: "taxi", p: "n.", t: "計程車", s: "Let's go home by taxi."},
{w: "teacher", p: "n.", t: "老師", s: "She is my English teacher."},
{w: "tell", p: "v.", t: "說", s: "Tell me a story, please."},
{w: "ten", p: "n.", t: "十", s: "Count from one to ten."},
{w: "tenth", p: "n. adj.", t: "第十", s: "It is the tenth of May."},
{w: "thick", p: "adj.", t: "厚的", s: "This book is very thick."},
{w: "thin", p: "adj.", t: "瘦的", s: "The thin boy is running."},
{w: "think", p: "v.", t: "想", s: "Let me think about it."},
{w: "third", p: "n. adj.", t: "第三", s: "He is the third student."},
{w: "thirteen", p: "n.", t: "十三", s: "There are thirteen boys."},
{w: "thirty", p: "n.", t: "三十", s: "Thirty days in April."},
{w: "thousand", p: "n.", t: "千", s: "One thousand people are here."},
{w: "three", p: "n.", t: "三", s: "I have three sisters."},
{w: "Thursday", p: "n.", t: "星期四", s: "Today is Thursday."},
{w: "ticket", p: "n.", t: "票", s: "Show me your ticket, please."},
{w: "time", p: "n.", t: "時間", s: "What time is it now?"},
{w: "today", p: "adv. n.", t: "今天", s: "Today is my birthday."},
{w: "tomorrow", p: "adv. n.", t: "明天", s: "See you tomorrow morning."},
{w: "tonight", p: "adv. n.", t: "今晚", s: "We have a party tonight."},
{w: "top", p: "n.", t: "頂端", s: "The cat is on top of the tree."},
{w: "train", p: "n.", t: "火車", s: "I go to Taipei by train."},
{w: "truck", p: "n.", t: "貨車", s: "The truck is very big."},
{w: "Tuesday", p: "n.", t: "星期二", s: "We have art class on Tuesday."},
{w: "twelve", p: "n.", t: "十二", s: "Twelve months in a year."},
{w: "twenty", p: "n.", t: "二十", s: "It costs twenty dollars."},
{w: "two", p: "n.", t: "二", s: "I have two red apples."},
{w: "uncle", p: "n.", t: "叔、舅", s: "My uncle is a doctor."},
{w: "under", p: "prep.", t: "在底下", s: "The ball is under the table."},
{w: "useful", p: "adj.", t: "有用的", s: "This dictionary is very useful."},
{w: "warm", p: "adj.", t: "溫暖", s: "The weather is warm in spring."},
{w: "weak", p: "adj.", t: "虛弱的", s: "I feel weak because of the cold."},
{w: "weather", p: "n.", t: "天氣", s: "How is the weather today?"},
{w: "Wednesday", p: "n.", t: "星期三", s: "Today is Wednesday."},
{w: "week", p: "n.", t: "週", s: "Seven days make a week."},
{w: "west", p: "n. adj. adv.", t: "西方", s: "The sun sets in the west."},
{w: "wet", p: "adj.", t: "濕的", s: "My shoes are wet."},
{w: "white", p: "adj. n.", t: "白色", s: "The white clouds are pretty."},
{w: "wife", p: "n.", t: "妻子", s: "My father loves his wife."},
{w: "wind", p: "n.", t: "風", s: "The wind is very strong."},
{w: "windy", p: "adj.", t: "多風的", s: "It is a windy day."},
{w: "winter", p: "n.", t: "冬天", s: "It is cold in winter."},
{w: "wood", p: "n.", t: "木材", s: "The desk is made of wood."},
{w: "worker", p: "n.", t: "工人", s: "The factory worker is busy."},
{w: "writer", p: "n.", t: "作家", s: "He is a famous writer."},
{w: "wrong", p: "adj.", t: "錯誤的", s: "Your answer is wrong."},
{w: "year", p: "n.", t: "年", s: "Happy New Year!"},
{w: "yellow", p: "adj. n.", t: "黃色", s: "The banana is yellow."},
{w: "yes(yeah)", p: "adv.", t: "是的", s: "Yes, I am a student."},
{w: "yesterday", p: "adv. n.", t: "昨天", s: "I was at home yesterday."},
{w: "you", p: "pron.", t: "你", s: "You are my best friend."},
{w: "young", p: "adj.", t: "年輕的", s: "The young boy can swim well."}
],
"Mover-A": [
{w: "able", p: "adj.", t: "能夠", s: "He is able to swim across the river."},
{w: "about", p: "prep.", t: "大約;關於", s: "The film is about a brave dog."},
{w: "afraid", p: "adj.", t: "害怕的", s: "Don't be afraid of making mistakes."},
{w: "after", p: "prep. conj.", t: "在~之後", s: "We played soccer after school."},
{w: "again", p: "adv.", t: "再一次", s: "Could you please say that again?"},
{w: "ago", p: "adv.", t: "以前", s: "I visited Taipei three years ago."},
{w: "agree", p: "v.", t: "同意", s: "I agree with your idea."},
{w: "all", p: "adj. pron.", t: "全部的", s: "All the students are in the gym."},
{w: "almost", p: "adv.", t: "幾乎", s: "Dinner is almost ready."},
{w: "already", p: "adv.", t: "已經", s: "I have already finished my work."},
{w: "also", p: "adv.", t: "也", s: "She is not only smart but also kind."},
{w: "America", p: "n.", t: "美國", s: "New York is a big city in America."},
{w: "American", p: "n. adj.", t: "美國人;美國的", s: "He is an American student."},
{w: "and", p: "conj.", t: "而且;和", s: "I like apples and oranges."},
{w: "angel", p: "n.", t: "天使", s: "The little girl looks like an angel."},
{w: "angry", p: "adj.", t: "生氣的", s: "Mom was angry because I was late."},
{w: "animal", p: "n.", t: "動物", s: "The tiger is a dangerous animal."},
{w: "another", p: "pron. adj.", t: "另一個", s: "Can I have another piece of cake?"},
{w: "answer", p: "n. v.", t: "答案;回答", s: "Please answer my question."},
{w: "any", p: "adj. pron.", t: "任何", s: "Do you have any questions?"},
{w: "anything", p: "pron.", t: "任何事", s: "Is there anything in the box?"},
{w: "apartment", p: "n.", t: "公寓", s: "They live in a small apartment."},
{w: "apple", p: "n.", t: "蘋果", s: "An apple a day keeps the doctor away."},
{w: "arrive", p: "v.", t: "到達", s: "What time did the train arrive?"},
{w: "as", p: "prep. conj.", t: "像~一樣;當作", s: "He is as tall as his father."},
{w: "ask", p: "v.", t: "詢問;要求", s: "Ask your teacher for help."},
{w: "away", p: "adv.", t: "離開;遠離", s: "Keep away from the fire."},
{w: "bag", p: "n.", t: "袋子", s: "The bag is full of heavy books."},
{w: "ball", p: "n.", t: "球", s: "Kick the ball into the goal."},
{w: "banana", p: "n.", t: "香蕉", s: "Monkeys like to eat bananas."},
{w: "band", p: "n.", t: "樂團", s: "He plays the drums in a rock band."},
{w: "basket", p: "n.", t: "籃子", s: "A basket full of fresh fruit."},
{w: "basketball", p: "n.", t: "籃球", s: "We play basketball after school."},
{w: "bathroom", p: "n.", t: "浴室", s: "Wash your hands in the bathroom."},
{w: "beach", p: "n.", t: "沙灘", s: "We like to walk on the beach."},
{w: "bear", p: "n. v.", t: "熊;承受", s: "The polar bear lives in the snow."},
{w: "beautiful", p: "adj.", t: "美麗的", s: "The sunset is very beautiful."},
{w: "because", p: "conj.", t: "因為", s: "I stayed home because it rained."},
{w: "bed", p: "n.", t: "床", s: "It's time to go to bed."},
{w: "bedroom", p: "n.", t: "臥室", s: "I have a computer in my bedroom."},
{w: "beef", p: "n.", t: "牛肉", s: "My favorite food is beef noodles."},
{w: "before", p: "prep. conj. adv.", t: "在~之前", s: "Wash your hands before dinner."},
{w: "bell", p: "n.", t: "鈴;鐘", s: "The school bell is ringing."},
{w: "belt", p: "n.", t: "皮帶;帶子", s: "Fasten your seat belt, please."},
{w: "bicycle(bike)", p: "n.", t: "腳踏車", s: "I ride my bicycle to the park."},
{w: "bird", p: "n.", t: "小鳥", s: "The bird is singing in the tree."},
{w: "birthday", p: "n.", t: "生日", s: "Happy birthday to you!"},
{w: "blow", p: "v. n.", t: "吹", s: "Blow out the candles on the cake."},
{w: "body", p: "n.", t: "身體", s: "Exercise is good for your body."},
{w: "borrow", p: "v.", t: "借入", s: "Can I borrow your pencil?"},
{w: "both", p: "pron. adj.", t: "兩者都", s: "Both of my brothers are tall."},
{w: "bottle", p: "n.", t: "瓶子", s: "A bottle of cold water."},
{w: "bowl", p: "n.", t: "碗", s: "I eat a bowl of rice for lunch."},
{w: "bread", p: "n.", t: "麵包", s: "I want some bread and butter."},
{w: "breakfast", p: "n.", t: "早餐", s: "What did you eat for breakfast?"},
{w: "bridge", p: "n.", t: "橋樑", s: "They are building a new bridge."},
{w: "bright", p: "adj.", t: "明亮的", s: "The stars are very bright tonight."},
{w: "burn", p: "v. n.", t: "燃燒;燒傷", s: "Don't burn the dry leaves."},
{w: "business", p: "n.", t: "生意;事情", s: "He travels on business."},
{w: "busy", p: "adj.", t: "忙碌的", s: "Dad is very busy this week."},
{w: "but", p: "conj.", t: "但是", s: "I'm tired, but I'm happy."},
{w: "butter", p: "n.", t: "奶油", s: "Put some butter on the toast."},
{w: "button", p: "n.", t: "按鈕;鈕扣", s: "Press the red button."},
{w: "by", p: "prep.", t: "在旁;搭乘;藉著", s: "I go to school by bus."},
{w: "cake", p: "n.", t: "蛋糕", s: "Mom made a chocolate cake."},
{w: "call", p: "v. n.", t: "打電話;呼叫", s: "Call me tonight, okay?"},
{w: "camera", p: "n.", t: "相機", s: "Smile at the camera!"},
{w: "candy", p: "n.", t: "糖果", s: "Don't eat too much candy."},
{w: "cap", p: "n.", t: "鴨舌帽", s: "He is wearing a blue cap."},
{w: "card", p: "n.", t: "卡片", s: "I sent a card to my teacher."},
{w: "care", p: "v. n.", t: "關心;在乎", s: "You should care about your health."},
{w: "carry", p: "v.", t: "搬運;攜帶", s: "The bag is too heavy to carry."},
{w: "cartoon", p: "n.", t: "卡通", s: "Children love watching cartoons."},
{w: "cat", p: "n.", t: "貓", s: "The cat is sleeping on the sofa."},
{w: "catch", p: "v. n.", t: "抓到;接住", s: "Catch the ball!"},
{w: "chair", p: "n.", t: "椅子", s: "Please sit on the chair."},
{w: "change", p: "v. n.", t: "改變;找零", s: "The weather changes quickly."},
{w: "check", p: "v. n.", t: "檢查", s: "Check your work again."},
{w: "cheese", p: "n.", t: "乳酪;起司", s: "I like cheese on my pizza."},
{w: "chicken", p: "n.", t: "雞肉;小雞", s: "Fried chicken tastes good."},
{w: "China", p: "n.", t: "中國", s: "The Great Wall is in China."},
{w: "chocolate", p: "n.", t: "巧克力", s: "A box of dark chocolate."},
{w: "chopsticks", p: "n.", t: "筷子", s: "We eat noodles with chopsticks."},
{w: "city", p: "n.", t: "城市", s: "I live in a big city."},
{w: "classmate", p: "n.", t: "同班同學", s: "He is my favorite classmate."},
{w: "clean", p: "v. adj.", t: "清掃;乾淨的", s: "Please clean the window."},
{w: "clock", p: "n.", t: "時鐘", s: "Look at the clock on the wall."},
{w: "close", p: "v. adj.", t: "關閉;接近的", s: "Please close the door."},
{w: "clothes", p: "n.", t: "衣服", s: "Put on your warm clothes."},
{w: "club", p: "n.", t: "社團", s: "Join the English club."},
{w: "coat", p: "n.", t: "外套", s: "It's cold. Put on your coat."},
{w: "Coke", p: "n.", t: "可樂", s: "I'd like a cold Coke, please."},
{w: "cold", p: "adj. n.", t: "冷的;感冒", s: "It is very cold in winter."},
{w: "come", p: "v.", t: "來臨;過來", s: "Come and see me tomorrow."},
{w: "cook", p: "v. n.", t: "烹飪;廚師", s: "My father is a good cook."},
{w: "copy", p: "v. n.", t: "影印;抄襲;副本", s: "Don't copy others' homework."},
{w: "cost", p: "v. n.", t: "花費;價值", s: "How much does it cost?"},
{w: "country", p: "n.", t: "國家;鄉下", s: "He lives in the country."},
{w: "cover", p: "v. n.", t: "覆蓋;封面", s: "The book has a blue cover."},
{w: "cow", p: "n.", t: "母牛", s: "The cow gives us milk."},
{w: "cross", p: "v. n.", t: "經過;越過;十字架", s: "Be careful when you cross the road."},
{w: "cry", p: "v. n.", t: "哭;大叫", s: "The baby started to cry."},
{w: "cup", p: "n.", t: "杯子", s: "A cup of hot tea."},
{w: "cut", p: "v. n.", t: "切;剪", s: "Cut the cake into pieces."},
{w: "dance", p: "v. n.", t: "跳舞", s: "She likes to dance to music."},
{w: "dangerous", p: "adj.", t: "危險的", s: "It is dangerous to play with fire."},
{w: "dark", p: "adj. n.", t: "黑暗的", s: "I'm afraid of the dark."},
{w: "date", p: "n. v.", t: "日期;約會", s: "What is the date today?"},
{w: "dear", p: "adj. interj.", t: "親愛的", s: "Oh dear! I forgot my keys."},
{w: "desk", p: "n.", t: "書桌", s: "Put your books on the desk."},
{w: "dining room", p: "n.", t: "飯廳", s: "We have dinner in the dining room."},
{w: "dinner", p: "n.", t: "晚餐", s: "What's for dinner tonight?"},
{w: "dog", p: "n.", t: "狗", s: "The dog is barking at the cat."},
{w: "door", p: "n.", t: "門", s: "Please open the door."},
{w: "dress", p: "n. v.", t: "洋裝;穿衣", s: "She is wearing a pink dress."},
{w: "drink", p: "v. n.", t: "喝;飲料", s: "Would you like a drink?"},
{w: "e-mail", p: "n. v.", t: "電子郵件", s: "Send me an e-mail."},
{w: "ease", p: "n. v.", t: "輕鬆;舒緩", s: "He passed the test with ease."},
{w: "eat", p: "v.", t: "吃", s: "Don't eat too much junk food."},
{w: "egg", p: "n.", t: "蛋", s: "I have an egg for breakfast."},
{w: "elephant", p: "n.", t: "大象", s: "The elephant is very big."},
{w: "enough", p: "adj. adv. pron.", t: "足夠", s: "I have had enough to eat."},
{w: "exciting", p: "adj.", t: "刺激的;令人興奮的", s: "The game was very exciting."},
{w: "excuse", p: "v. n.", t: "藉口;原諒", s: "Excuse me, where is the station?"},
{w: "exist", p: "v.", t: "存在", s: "Do you believe ghosts exist?"},
{w: "exit", p: "n. v.", t: "出口;退出", s: "Follow the exit signs."},
{w: "famous", p: "adj.", t: "有名的", s: "He is a famous singer."},
{w: "fish", p: "n. v.", t: "魚;釣魚", s: "There are many fish in the lake."},
{w: "floor", p: "n.", t: "地板;樓層", s: "My room is on the third floor."},
{w: "flower", p: "n.", t: "花", s: "The flowers smell sweet."},
{w: "fly", p: "v. n.", t: "飛;蒼蠅", s: "Birds can fly in the sky."},
{w: "food", p: "n.", t: "食物", s: "Pizza is my favorite food."},
{w: "fork", p: "n.", t: "叉子", s: "I use a fork to eat noodles."},
{w: "free", p: "adj. adv. v.", t: "空閒的;免費的", s: "Are you free this weekend?"},
{w: "friend", p: "n.", t: "朋友", s: "He is my best friend."},
{w: "from", p: "prep.", t: "從~而來", s: "Where are you from?"},
{w: "fruit", p: "n.", t: "水果", s: "I like to eat fresh fruit."},
{w: "funny", p: "adj.", t: "好笑的", s: "The clown is very funny."},
{w: "glass", p: "n.", t: "玻璃杯;玻璃", s: "A glass of orange juice."},
{w: "glove", p: "n.", t: "手套", s: "Put on your gloves. It's cold."},
{w: "goat", p: "n.", t: "山羊", s: "The goat is eating grass."},
{w: "grass", p: "n.", t: "草地", s: "Don't walk on the grass."},
{w: "ham", p: "n.", t: "火腿", s: "I want a ham sandwich."},
{w: "hamburger", p: "n.", t: "漢堡", s: "Let's go and get a hamburger."},
{w: "happy", p: "adj.", t: "高興的", s: "Happy birthday to you!"},
{w: "hat", p: "n.", t: "帽子", s: "He is wearing a black hat."},
{w: "hate", p: "v. n.", t: "痛恨", s: "I hate cold weather."},
{w: "help", p: "v. n.", t: "幫助", s: "Can you help me, please?"},
{w: "hill", p: "n.", t: "山丘", s: "They ran up the hill."},
{w: "hope", p: "v. n.", t: "希望", s: "I hope you have a nice day."}
],
"Mover-B": [
{w: "horse", p: "n.", t: "馬", s: "Can you ride a horse?"},
{w: "hot", p: "adj.", t: "熱的", s: "It's very hot in the summer."},
{w: "hot dog", p: "n.", t: "熱狗", s: "I want a hot dog for lunch."},
{w: "hotel", p: "n.", t: "旅館", s: "We are staying in a hotel near the beach."},
{w: "house", p: "n.", t: "房子", s: "They live in a big white house."},
{w: "ice cream", p: "n.", t: "冰淇淋", s: "I like chocolate ice cream."},
{w: "idea", p: "n.", t: "點子/主意", s: "That is a great idea!"},
{w: "Internet", p: "n.", t: "網際網路", s: "I use the Internet to do my homework."},
{w: "island", p: "n.", t: "島嶼", s: "Taiwan is a beautiful island."},
{w: "jacket", p: "n.", t: "夾克", s: "Put on your jacket. It's cold outside."},
{w: "juice", p: "n.", t: "果汁", s: "Would you like some orange juice?"},
{w: "keep", p: "v.", t: "保持", s: "Please keep your room clean."},
{w: "kiss", p: "v. n.", t: "親吻", s: "Give your mom a kiss."},
{w: "kitchen", p: "n.", t: "廚房", s: "Mom is cooking dinner in the kitchen."},
{w: "knife", p: "n.", t: "刀子", s: "Be careful with that sharp knife."},
{w: "lake", p: "n.", t: "湖", s: "We went fishing at the lake."},
{w: "lamp", p: "n.", t: "燈", s: "Turn on the lamp. It's too dark."},
{w: "land", p: "n. v.", t: "土地/降落", s: "The plane will land in ten minutes."},
{w: "laugh", p: "v. n.", t: "笑", s: "The funny story made us laugh."},
{w: "leaf", p: "n.", t: "樹葉", s: "The red leaf fell from the tree."},
{w: "lend", p: "v.", t: "借出", s: "Can you lend me your ruler?"},
{w: "letter", p: "n.", t: "信/字母", s: "I am writing a letter to my friend."},
{w: "like", p: "v. prep.", t: "喜歡/像", s: "I like apples more than oranges."},
{w: "line", p: "n. v.", t: "線/排隊", s: "Please stand in a line."},
{w: "lion", p: "n.", t: "獅子", s: "The lion is the king of the forest."},
{w: "live", p: "v.", t: "生活/居住", s: "I live in a big city."},
{w: "living room", p: "n.", t: "客廳", s: "We watch TV in the living room."},
{w: "love", p: "v. n.", t: "喜愛/愛", s: "I love my family very much."},
{w: "lunch", p: "n.", t: "午餐", s: "What's for lunch today?"},
{w: "map", p: "n.", t: "地圖", s: "We need a map to find the way."},
{w: "meal", p: "n.", t: "餐", s: "Breakfast is the most important meal."},
{w: "meat", p: "n.", t: "肉", s: "I don't eat much meat."},
{w: "meet", p: "v. n.", t: "相遇/見面", s: "Nice to meet you."},
{w: "meeting", p: "n.", t: "會議", s: "Dad has a meeting this afternoon."},
{w: "milk", p: "n.", t: "牛奶", s: "Drink a glass of milk every day."},
{w: "Miss", p: "n.", t: "小姐 (稱呼)", s: "Miss Lin is our English teacher."},
{w: "monkey", p: "n.", t: "猴子", s: "The monkey is eating a banana."},
{w: "mountain", p: "n.", t: "山", s: "Let's climb the mountain together."},
{w: "mouse", p: "n.", t: "老鼠", s: "The cat is chasing a mouse."},
{w: "noise", p: "n.", t: "噪音", s: "Stop making so much noise!"},
{w: "noodle", p: "n.", t: "麵條", s: "I like to eat beef noodles."},
{w: "number", p: "n.", t: "數字/號碼", s: "What is your lucky number?"},
{w: "pants", p: "n.", t: "褲子", s: "He is wearing blue pants."},
{w: "park", p: "n. v.", t: "公園/停車", s: "Let's go for a walk in the park."},
{w: "party", p: "n.", t: "宴會/派對", s: "I'm going to a birthday party."},
{w: "pay", p: "v. n.", t: "付賬/工資", s: "You have to pay for the tickets."},
{w: "photo", p: "n.", t: "照片", s: "Take a photo of the beautiful flowers."},
{w: "piano", p: "n.", t: "鋼琴", s: "She plays the piano very well."},
{w: "picnic", p: "n. v.", t: "野餐", s: "Let's have a picnic in the park."},
{w: "pie", p: "n.", t: "派", s: "Mom made an apple pie."},
{w: "pig", p: "n.", t: "豬", s: "The pig is fat and pink."},
{w: "pizza", p: "n.", t: "披薩", s: "I want to eat seafood pizza."},
{w: "plan", p: "n. v.", t: "計畫", s: "What is your plan for the summer?"},
{w: "play", p: "v. n.", t: "玩/戲劇", s: "I like to play basketball."},
{w: "polite", p: "adj.", t: "禮貌的", s: "It is important to be polite to others."},
{w: "rabbit", p: "n.", t: "兔子", s: "The white rabbit has long ears."},
{w: "railway", p: "n.", t: "鐵路", s: "The railway station is over there."},
{w: "restaurant", p: "n.", t: "餐廳", s: "Let's go to an Italian restaurant."},
{w: "rice", p: "n.", t: "米/米飯", s: "We eat rice every day."},
{w: "ring", p: "n. v.", t: "戒指/按鈴", s: "She is wearing a gold ring."},
{w: "river", p: "n.", t: "河流", s: "The river is very long and clean."},
{w: "rose", p: "n.", t: "玫瑰", s: "He gave his mother a red rose."},
{w: "row", p: "n. v.", t: "排/划船/爭吵", s: "Sit in the front row, please."},
{w: "sad", p: "adj.", t: "傷心的", s: "Don't be sad. Everything will be fine."},
{w: "salad", p: "n.", t: "沙拉", s: "I want a fruit salad."},
{w: "salt", p: "n.", t: "鹽巴", s: "Please pass me the salt."},
{w: "sandwich", p: "n.", t: "三明治", s: "I have a ham sandwich for lunch."},
{w: "sea", p: "n.", t: "海", s: "There are many fish in the sea."},
{w: "seed", p: "n.", t: "種子", s: "Birds like to eat seeds."},
{w: "seek", p: "v.", t: "追尋/尋找", s: "They seek for the truth."},
{w: "send", p: "v.", t: "傳送/寄", s: "I will send you an e-mail."},
{w: "set", p: "n. v.", t: "台/套/設定", s: "A TV set; set the table for dinner."},
{w: "sheep", p: "n.", t: "綿羊", s: "A sheep gives us wool."},
{w: "shirt", p: "n.", t: "襯衫", s: "Wash your white shirt."},
{w: "shoe(s)", p: "n.", t: "鞋子", s: "Put on your shoes."},
{w: "shy", p: "adj.", t: "害羞的", s: "The boy is very shy."},
{w: "sing", p: "v.", t: "唱歌", s: "She likes to sing English songs."},
{w: "singer", p: "n.", t: "歌手", s: "He is a famous singer."},
{w: "skirt", p: "n.", t: "裙子", s: "The little girl is wearing a red skirt."},
{w: "smile", p: "v. n.", t: "微笑", s: "She greeted us with a big smile."},
{w: "snake", p: "n.", t: "蛇", s: "I am afraid of snakes."},
{w: "soap", p: "n.", t: "肥皂", s: "Wash your hands with soap."},
{w: "sofa", p: "n.", t: "沙發", s: "The sofa in the living room is soft."},
{w: "sorry", p: "adj.", t: "抱歉/遺憾", s: "I am sorry for being late."},
{w: "soup", p: "n.", t: "湯", s: "Chicken soup tastes good."},
{w: "speak", p: "v.", t: "說/講(語言)", s: "I can speak English."},
{w: "speed", p: "n. v.", t: "速度", s: "The car is traveling at high speed."},
{w: "spoon", p: "n.", t: "湯匙", s: "Eat your soup with a spoon."},
{w: "sports", p: "n.", t: "運動", s: "What sports do you like?"},
{w: "stand", p: "v. n.", t: "站立/忍受", s: "Please stand up."},
{w: "stay", p: "v. n.", t: "停留/待著", s: "Stay here with me."},
{w: "sugar", p: "n.", t: "糖", s: "Don't put too much sugar in my tea."},
{w: "super", p: "adj.", t: "超級的", s: "He is a super soccer player."},
{w: "supermarket", p: "n.", t: "超級市場", s: "We buy food at the supermarket."},
{w: "sweater", p: "n.", t: "毛衣", s: "Wear a sweater if you feel cold."},
{w: "table", p: "n.", t: "桌子", s: "The dinner is on the table."},
{w: "tea", p: "n.", t: "茶", s: "Would you like a cup of tea?"},
{w: "telephone (phone)", p: "n. v.", t: "電話", s: "The telephone is ringing."},
{w: "television (TV)", p: "n.", t: "電視", s: "Don't watch too much television."},
{w: "thank", p: "v. n.", t: "感謝", s: "Thank you for your help."},
{w: "tiger", p: "n.", t: "老虎", s: "The tiger has orange and black stripes."},
{w: "tomato", p: "n.", t: "番茄", s: "I like tomato soup."},
{w: "travel", p: "v. n.", t: "旅行", s: "I want to travel around the world."},
{w: "tree", p: "n.", t: "樹", s: "There is a big tree in front of our house."},
{w: "uniform", p: "n. adj.", t: "制服", s: "Students wear uniforms to school."},
{w: "vegetable", p: "n.", t: "蔬菜", s: "Eat more fresh vegetables."},
{w: "video", p: "n. adj.", t: "影片", s: "Let's watch a funny video."},
{w: "visit", p: "v. n.", t: "拜訪/參觀", s: "I'll visit my grandma this weekend."},
{w: "wall", p: "n.", t: "牆壁", s: "There is a clock on the wall."},
{w: "wash", p: "v. n.", t: "洗", s: "Wash your hands before dinner."},
{w: "water", p: "n. v.", t: "水/澆水", s: "Drink plenty of water."},
{w: "wear", p: "v.", t: "穿/戴", s: "She is wearing a red hat."},
{w: "window", p: "n.", t: "窗戶", s: "Please open the window."},
{w: "wonderful", p: "adj.", t: "很棒的", s: "Have a wonderful trip!"},
{w: "worry", p: "v. n.", t: "擔憂", s: "Don't worry about the test."},
{w: "zoo", p: "n.", t: "動物園", s: "We saw many animals at the zoo."}
],
"Runner-A": [
{w: "asleep", p: "adj.", t: "睡著", s: "The baby is fast asleep in the bed."},
{w: "basic", p: "adj.", t: "基礎的", s: "Learning ABC is the basic step of English."},
{w: "cowboy", p: "n.", t: "牛仔", s: "The cowboy is riding a big horse."},
{w: "decide", p: "v.", t: "決定", s: "I can't decide which toy to buy."},
{w: "delicious", p: "adj.", t: "好吃的", s: "Mom made a delicious chocolate cake."},
{w: "die", p: "v.", t: "死", s: "The flowers will die without water."},
{w: "different", p: "adj.", t: "不同的", s: "We are in different classes."},
{w: "difficult", p: "adj.", t: "困難的", s: "This math question is very difficult."},
{w: "dirty", p: "adj.", t: "骯髒的", s: "Wash your dirty hands before dinner."},
{w: "dollar", p: "n.", t: "元", s: "The hot dog costs one dollar."},
{w: "down", p: "adv.", t: "向下", s: "Please sit down and listen to me."},
{w: "draw", p: "v.", t: "畫", s: "Can you draw a picture of a house?"},
{w: "during", p: "prep.", t: "在 ~ 期間", s: "I slept during the long movie."},
{w: "each", p: "adv. adj.", t: "每一", s: "Each student has a new notebook."},
{w: "ear", p: "n.", t: "耳朵", s: "We listen to music with our ears."},
{w: "early", p: "adv. adj.", t: "早", s: "I wake up early every morning."},
{w: "easy", p: "adj.", t: "簡單的", s: "The test was very easy for me."},
{w: "either", p: "adj. pron. adv.", t: "也 (不)", s: "I don't like coffee, and he doesn't either."},
{w: "end", p: "n. v.", t: "結束", s: "Wait for the end of the show."},
{w: "enjoy", p: "v.", t: "享受", s: "I enjoy playing basketball with friends."},
{w: "even", p: "adv.", t: "甚至", s: "He can't even ride a bicycle."},
{w: "ever", p: "adv.", t: "曾經", s: "Have you ever been to a zoo?"},
{w: "every", p: "adj.", t: "每一個", s: "I exercise every day to stay healthy."},
{w: "everything", p: "pron.", t: "每件事", s: "Everything will be okay. Don't worry."},
{w: "except", p: "prep.", t: "除 ~ 之外", s: "Everyone is here except Tom."},
{w: "eye", p: "n.", t: "眼睛", s: "The cat has big green eyes."},
{w: "face", p: "v. n.", t: "面對；臉", s: "Wash your face; we must face the problem."},
{w: "fact", p: "n.", t: "事實", s: "In fact, I don't like chocolate."},
{w: "factory", p: "n.", t: "工廠", s: "My uncle works in a toy factory."},
{w: "false", p: "adj.", t: "錯誤的", s: "Is the answer true or false?"},
{w: "fan", p: "n.", t: "迷;風扇", s: "He is a big fan of baseball."},
{w: "fee", p: "n.", t: "費用", s: "You have to pay the entrance fee."},
{w: "fill", p: "v.", t: "充滿", s: "Please fill the bottle with water."},
{w: "follow", p: "v.", t: "跟隨;遵守", s: "Follow the rules, and follow me."},
{w: "for", p: "prep.", t: "給;為了", s: "This birthday gift is for you."},
{w: "foreign", p: "adj.", t: "外國的", s: "She speaks a foreign language."},
{w: "friendly", p: "adj.", t: "友善的", s: "The people here are very friendly."},
{w: "full", p: "adj.", t: "充滿的;飽的", s: "The room is full of people."},
{w: "fun", p: "n. adj.", t: "樂趣", s: "Playing games is great fun."},
{w: "game", p: "n.", t: "遊戲", s: "Let's play a computer game."},
{w: "garden", p: "n.", t: "花園", s: "There are many flowers in the garden."},
{w: "give", p: "v.", t: "給", s: "Give me a hand with this box."},
{w: "glad", p: "adj.", t: "高興的", s: "I am glad to see you again."},
{w: "go", p: "v.", t: "去", s: "Let's go to the park."},
{w: "goodbye", p: "n. interj.", t: "再見", s: "Say goodbye to your friends."},
{w: "grade", p: "n.", t: "成績；級數", s: "He got a good grade on the math test."},
{w: "great", p: "adj.", t: "很棒的", s: "That is a great idea!"},
{w: "ground", p: "n.", t: "地板;地面", s: "Don't sit on the cold ground."},
{w: "group", p: "n.", t: "群;組", s: "Work together in a small group."},
{w: "hair", p: "n.", t: "頭髮", s: "She has long black hair."},
{w: "hand", p: "n. v.", t: "手", s: "Wash your hands before eating."},
{w: "happen", p: "v.", t: "發生", s: "What happened to your leg?"},
{w: "he", p: "pron.", t: "他", s: "He is my best friend."},
{w: "head", p: "n.", t: "頭", s: "My head hurts today."},
{w: "healthy", p: "adj.", t: "健康的", s: "Eating fruit is very healthy."},
{w: "heart", p: "n.", t: "心臟", s: "Listen to your heart beat."},
{w: "hello", p: "n. interj.", t: "哈囉", s: "Say hello to your new classmate."},
{w: "here", p: "adv.", t: "這裡", s: "Come here and help me."},
{w: "hi", p: "n. interj.", t: "嗨", s: "Hi! How are you doing?"},
{w: "high", p: "adj. adv.", t: "高的", s: "The bird is flying high in the sky."},
{w: "holiday", p: "n.", t: "假日", s: "We are going to Taipei on holiday."},
{w: "home", p: "n. adv.", t: "家；在家", s: "I want to go home now."},
{w: "hospital", p: "n.", t: "醫院", s: "The sick man is in the hospital."},
{w: "how", p: "adv.", t: "如何", s: "How do you go to school?"},
{w: "hungry", p: "adj.", t: "饑餓的", s: "I am hungry; let's eat lunch."},
{w: "hurry", p: "n. v.", t: "趕快;急促", s: "Hurry up, or we will be late."},
{w: "I", p: "pron.", t: "我", s: "I am a student at this school."},
{w: "if", p: "conj.", t: "如果", s: "If it rains, we will stay home."},
{w: "important", p: "adj.", t: "重要的", s: "Studying hard is very important."},
{w: "inside", p: "adv. prep. adj. n.", t: "在裡面", s: "It is cold outside, go inside."},
{w: "it", p: "pron.", t: "它", s: "It is a very cute cat."},
{w: "join", p: "v.", t: "參與;加入", s: "Would you like to join our club?"},
{w: "jump", p: "v. n.", t: "跳", s: "Can you jump over the small box?"},
{w: "just", p: "adv.", t: "只是;剛剛", s: "I just finished my homework."},
{w: "key", p: "n.", t: "鑰匙", s: "Where did I put my car key?"},
{w: "kind", p: "adj. n.", t: "和善的；種類", s: "She is very kind; what kind of fruit is this?"},
{w: "knock", p: "v. n.", t: "敲", s: "Knock on the door before you enter."},
{w: "language", p: "n.", t: "語言", s: "English is a global language."},
{w: "large", p: "adj.", t: "大的", s: "The elephant is a very large animal."},
{w: "last", p: "adj. adv. v. n.", t: "最後的;上一個", s: "I saw him last night."},
{w: "late", p: "adj. adv.", t: "遲的", s: "Don't be late for class."},
{w: "later", p: "adv. adj.", t: "稍後", s: "See you later!"},
{w: "lazy", p: "adj.", t: "懶惰的", s: "Don't be lazy; help me with the dishes."},
{w: "learn", p: "v.", t: "學習", s: "I want to learn how to cook."},
{w: "leg", p: "n.", t: "腿", s: "The table has four legs."},
{w: "lesson", p: "n.", t: "課程", s: "Today's lesson is about animals."},
{w: "let", p: "v.", t: "讓", s: "Let me help you with that bag."},
{w: "library", p: "n.", t: "圖書館", s: "I like to study in the library."},
{w: "lie", p: "n. v.", t: "說謊;躺", s: "Don't tell a lie to me."},
{w: "life", p: "n.", t: "一生;生命", s: "He lived a long and happy life."},
{w: "list", p: "n. v.", t: "名單;清單", s: "Make a shopping list."},
{w: "listen", p: "v.", t: "聽", s: "Listen to the teacher carefully."},
{w: "look", p: "v. n.", t: "看", s: "Look at the beautiful sunset."},
{w: "loud", p: "adj. adv.", t: "大聲的", s: "The music is too loud."},
{w: "low", p: "adj. adv.", t: "低的; 低地", s: "The sun is low in the sky."},
{w: "machine", p: "n.", t: "機器", s: "The washing machine is broken."},
{w: "make", p: "v.", t: "做；決定", s: "I will make a cake for her."},
{w: "market", p: "n.", t: "市場", s: "Mom buys vegetables at the market."},
{w: "matter", p: "v. n.", t: "重要;事情", s: "It doesn't matter to me."},
{w: "maybe", p: "adv.", t: "可能", s: "Maybe it will rain tomorrow."},
{w: "medicine", p: "n.", t: "藥物", s: "Take your medicine on time."},
{w: "mind", p: "n. v.", t: "心; 介意", s: "Do you mind if I sit here?"},
{w: "mistake", p: "n. v.", t: "錯誤", s: "I made a mistake in the test."},
{w: "modern", p: "adj.", t: "現代的", s: "This is a very modern city."},
{w: "moment", p: "n.", t: "時刻", s: "Wait for a moment, please."},
{w: "money", p: "n.", t: "錢", s: "Save your money for the future."},
{w: "most", p: "adj. adv. pron.", t: "最多的", s: "Most students like to play games."},
{w: "move", p: "v. n.", t: "感動；搬移", s: "The story really moved me."},
{w: "museum", p: "n.", t: "博物館", s: "We visited the art museum."},
{w: "must", p: "modal v.", t: "必須", s: "You must do your homework now."},
{w: "name", p: "n. v.", t: "名字", s: "What is your name?"},
{w: "need", p: "v. n.", t: "需要", s: "I need some help with this."},
{w: "never", p: "adv.", t: "從不", s: "I have never been to London."},
{w: "news", p: "n.", t: "新聞", s: "Did you hear the good news?"},
{w: "nice", p: "adj.", t: "好的", s: "It is nice to meet you."},
{w: "no", p: "adv. adj. n.", t: "不", s: "No, I am not a doctor."},
{w: "nobody", p: "pron. n.", t: "沒有人", s: "Nobody was in the classroom."},
{w: "nose", p: "n.", t: "鼻子", s: "Touch your nose with your finger."},
{w: "not", p: "adv.", t: "不是", s: "She is not my sister."},
{w: "nothing", p: "pron. n. adv.", t: "沒有", s: "There is nothing in the box."},
{w: "nurse", p: "n. v.", t: "護士", s: "The nurse is kind to her patients."},
{w: "of", p: "prep.", t: "屬於 ~ 的", s: "The color of the sky is blue."},
{w: "off", p: "adv. prep. adj.", t: "中斷(水電);離開", s: "Turn off the light, please."},
{w: "office", p: "n.", t: "辦公室", s: "He is working in the office."},
{w: "often", p: "adv.", t: "經常", s: "I often go to the library."},
{w: "once", p: "adv. conj. n.", t: "一次", s: "I have been to Paris once."},
{w: "only", p: "adv. adj.", t: "只有", s: "He is the only child in his family."},
{w: "open", p: "v. adj.", t: "打開", s: "Open the window, please."},
{w: "or", p: "conj.", t: "或者", s: "Do you want tea or coffee?"},
{w: "other", p: "adj. pron.", t: "其他的", s: "Where are the other students?"},
{w: "outside", p: "adv. prep. adj. n.", t: "外面", s: "Let's go and play outside."},
{w: "over", p: "prep. adv. adj.", t: "在…之上;結束", s: "The game is over."},
{w: "own", p: "v. adj. pron.", t: "擁有;自己的", s: "I want to own my own house."},
{w: "page", p: "n. v.", t: "頁", s: "Turn to page ten, please."},
{w: "pair", p: "n. v.", t: "一雙", s: "I need a new pair of shoes."},
{w: "parent", p: "n.", t: "雙親之一", s: "Obey your parents."},
{w: "people", p: "n.", t: "人們", s: "Many people like to eat pizza."},
{w: "perhaps", p: "adv.", t: "或許", s: "Perhaps we can go together."},
{w: "person", p: "n.", t: "人", s: "He is a very nice person."},
{w: "pick", p: "v. n.", t: "撿拾;挑選", s: "Pick up the trash on the floor."},
{w: "picture", p: "n. v.", t: "圖畫", s: "Draw a picture of a cat."},
{w: "piece", p: "n. v.", t: "一張，一片", s: "Can I have a piece of cake?"},
{w: "please", p: "v. adv.", t: "請求;請", s: "Please help me with this."},
{w: "police", p: "n.", t: "警方", s: "Call the police right now."},
{w: "popular", p: "adj.", t: "受歡迎的", s: "He is a popular singer."},
{w: "possible", p: "adj.", t: "有可能的", s: "It is possible that it will rain."},
{w: "practice", p: "n. v.", t: "練習", s: "Practice makes perfect."},
{w: "problem", p: "n.", t: "問題", s: "What is the problem?"},
{w: "pull", p: "v. n.", t: "拉", s: "Pull the door, don't push it."},
{w: "push", p: "v. n.", t: "推", s: "Push the button to start."}
],
"Runner-B": [
{w: "put", p: "v.", t: "放", s: "Please put your books in the bag."},
{w: "question", p: "n. v.", t: "問題", s: "Do you have any questions about the lesson?"},
{w: "quick", p: "adj. adv.", t: "快速的", s: "Be quick, or we will miss the bus."},
{w: "quiet", p: "adj. n. v.", t: "安靜的", s: "Please be quiet in the library."},
{w: "quite", p: "adv.", t: "非常，相當", s: "The soup is quite hot."},
{w: "race", p: "n. v.", t: "競賽", s: "He won the running race."},
{w: "radio", p: "n. v.", t: "收音機", s: "My grandpa likes to listen to the radio."},
{w: "reach", p: "v. n.", t: "抵達;觸及", s: "Can you reach the book on the top shelf?"},
{w: "read", p: "v. n.", t: "讀", s: "I like to read stories before bed."},
{w: "ready", p: "adj. v.", t: "準備好", s: "Are you ready for the party?"},
{w: "really", p: "adv.", t: "真地", s: "I really like this movie."},
{w: "remember", p: "v.", t: "記得", s: "Remember to turn off the light."},
{w: "rest", p: "n. v.", t: "休息；其他", s: "Take a rest if you are tired."},
{w: "room", p: "n. v.", t: "房間", s: "My room is clean and tidy."},
{w: "round", p: "adj. n. v.", t: "圓的", s: "The earth is round."},
{w: "same", p: "adj. pron. adv.", t: "同樣的", s: "We are in the same school."},
{w: "save", p: "v. n.", t: "儲存;節省", s: "Save your money in the bank."},
{w: "seat", p: "n. v.", t: "位子", s: "Please take a seat."},
{w: "serious", p: "adj.", t: "嚴重的;認真的", s: "This is a serious problem."},
{w: "several", p: "adj. pron.", t: "好幾個", s: "I have several friends in Taipei."},
{w: "sharp", p: "adj. adv.", t: "銳利的", s: "Be careful with the sharp knife."},
{w: "show", p: "n. v.", t: "表演;展示", s: "Show me your new toy, please."},
{w: "sick", p: "adj. n.", t: "生病的", s: "I stayed home because I was sick."},
{w: "side", p: "n. adj. v.", t: "旁邊", s: "Stand on this side of the line."},
{w: "sir", p: "n.", t: "先生", s: "Yes, sir. How can I help you?"},
{w: "size", p: "n. v.", t: "尺寸", s: "What size is that T-shirt?"},
{w: "slow", p: "adj. adv. v.", t: "緩慢的", s: "Snails are very slow."},
{w: "so", p: "adv. conj. pron.", t: "如此;所以", s: "I am so happy today."},
{w: "socks", p: "n.", t: "襪子", s: "I need a pair of clean socks."},
{w: "some", p: "adj. pron. adv.", t: "一些", s: "Would you like some milk?"},
{w: "something", p: "pron.", t: "一些事", s: "I have something to tell you."},
{w: "song", p: "n.", t: "歌曲", s: "Let's sing a happy song."},
{w: "soon", p: "adv.", t: "很快", s: "See you soon!"},
{w: "start", p: "v. n.", t: "開始", s: "The movie will start at seven."},
{w: "still", p: "adv. adj. n. v.", t: "仍然", s: "It is still raining outside."},
{w: "stop", p: "v. n.", t: "停止", s: "Stop talking and open your books."},
{w: "story", p: "n.", t: "故事", s: "Tell me a bedtime story."},
{w: "study", p: "v. n.", t: "研讀", s: "I study English every night."},
{w: "sun", p: "n. v.", t: "太陽", s: "The sun is very bright today."},
{w: "sure", p: "adj. adv.", t: "確定的;了解的", s: "Are you sure about that?"},
{w: "talk", p: "v. n.", t: "談話", s: "Don't talk in class."},
{w: "tall", p: "adj.", t: "高的", s: "He is a tall boy."},
{w: "teach", p: "v. n.", t: "教書", s: "Mrs. Lin teaches us music."},
{w: "team", p: "n. v.", t: "團隊", s: "We are on the same team."},
{w: "test", p: "n. v.", t: "測驗", s: "I have a math test tomorrow."},
{w: "Thanksgiving", p: "n.", t: "感恩節", s: "We eat turkey on Thanksgiving."},
{w: "that", p: "pron. adj. conj. adv.", t: "那", s: "That is my bicycle."},
{w: "the", p: "art.", t: "這；那", s: "The sun rises in the east."},
{w: "there", p: "adv. n. pron.", t: "那裡", s: "The bookstore is over there."},
{w: "these", p: "pron. adj.", t: "這些", s: "These books are very heavy."},
{w: "they", p: "pron.", t: "他們", s: "They are my classmates."},
{w: "thing", p: "n.", t: "東西", s: "What is that thing on the table?"},
{w: "this", p: "pron. adj. adv.", t: "這個", s: "This is a present for you."},
{w: "those", p: "pron. adj.", t: "那些", s: "Those birds are singing."},
{w: "to", p: "prep. adv.", t: "到、向", s: "I go to school by bus."},
{w: "too", p: "adv.", t: "太；也", s: "I am too tired to run."},
{w: "total", p: "n. adj. v.", t: "總數", s: "What is the total number of students?"},
{w: "town", p: "n.", t: "城鎮", s: "My grandma lives in a small town."},
{w: "trash", p: "n. v.", t: "垃圾", s: "Don't throw trash on the ground."},
{w: "trouble", p: "n. v.", t: "麻煩", s: "I am in trouble now."},
{w: "try", p: "v. n.", t: "嘗試", s: "Try your best on the test."},
{w: "turn", p: "v. n.", t: "轉向；輪次", s: "It's your turn to play."},
{w: "until", p: "conj. prep.", t: "直到", s: "I stayed there until five o'clock."},
{w: "up", p: "adv. prep. adj. n. v.", t: "向上", s: "Stand up, please."},
{w: "use", p: "v. n.", t: "使用", s: "May I use your pen?"},
{w: "usually", p: "adv.", t: "經常", s: "I usually go to bed at ten."},
{w: "very", p: "adv. adj.", t: "非常", s: "Thank you very much."},
{w: "wait", p: "v. n.", t: "等待", s: "Wait for me at the gate."},
{w: "walk", p: "v. n.", t: "走路", s: "Let's walk to school together."},
{w: "want", p: "v. n.", t: "想要", s: "I want a cup of water."},
{w: "way", p: "n. adv.", t: "方法、道路", s: "This is the way to the park."},
{w: "we", p: "pron.", t: "我們", s: "We are best friends."},
{w: "welcome", p: "v. n. adj. interj.", t: "歡迎", s: "Welcome to our house."},
{w: "well", p: "adv. adj. interj. n. v.", t: "很好", s: "You did a very well job."},
{w: "what", p: "pron. adj. adv. interj.", t: "什麼", s: "What is your favorite color?"},
{w: "when", p: "adv. conj. n.", t: "何時", s: "When is your birthday?"},
{w: "where", p: "adv. conj. n.", t: "哪裡", s: "Where do you live?"},
{w: "whether", p: "conj.", t: "是否;無論", s: "I don't know whether he will come."},
{w: "which", p: "pron. adj.", t: "哪一個", s: "Which one do you like?"},
{w: "who", p: "pron.", t: "誰", s: "Who is that tall man?"},
{w: "whose", p: "pron. adj.", t: "誰的", s: "Whose bag is this?"},
{w: "why", p: "adv. n. interj.", t: "為什麼", s: "Why are you crying?"},
{w: "will(would)", p: "modal v.", t: "將要", s: "I will go to the park tomorrow."},
{w: "wish", p: "v. n.", t: "但願;祝福", s: "I wish you a Merry Christmas."},
{w: "without", p: "prep. adv. conj.", t: "沒有", s: "I can't see without my glasses."},
{w: "woman", p: "n.", t: "女人", s: "That woman is my aunt."},
{w: "word", p: "n. v. interj.", t: "字", s: "What does this word mean?"},
{w: "work", p: "v. n.", t: "工作", s: "My dad goes to work by car."},
{w: "world", p: "n.", t: "世界", s: "There are many countries in the world."},
{w: "yet", p: "adv. conj.", t: "尚未", s: "I haven't finished my dinner yet."},
{w: "a few", p: "adj. pron.", t: "一些(可數)", s: "I have a few friends in class."},
{w: "a little", p: "adj. adv. pron.", t: "一些(不可數)", s: "Give me a little water, please."},
{w: "a lot", p: "adv. n. pron.", t: "許多", s: "Thank you a lot."},
{w: "airplane(plane)", p: "n.", t: "飛機", s: "I go to America by airplane."},
{w: "always", p: "adv.", t: "總是", s: "He always gets up early."},
{w: "anyone", p: "pron.", t: "任何人", s: "Does anyone know the answer?"},
{w: "apologize", p: "v.", t: "道歉", s: "You should apologize to her."},
{w: "appear", p: "v.", t: "出現", s: "A rainbow appeared in the sky."},
{w: "argue", p: "v.", t: "爭辯", s: "Don't argue with your parents."},
{w: "arm", p: "n. v.", t: "手臂", s: "My left arm hurts."},
{w: "army", p: "n.", t: "軍隊", s: "He joined the army last year."},
{w: "available", p: "adj.", t: "可得到的;有效的", s: "Are there any tickets available?"},
{w: "backward", p: "adj. adv.", t: "向後的", s: "He took a backward step."},
{w: "bakery", p: "n.", t: "麵包店", s: "The bakery smells like fresh bread."},
{w: "bank", p: "n. v.", t: "銀行", s: "I need to go to the bank."},
{w: "barbecue", p: "v. n.", t: "烤肉", s: "We had a barbecue in the yard."},
{w: "base", p: "n. v.", t: "底部;根基", s: "The lamp has a heavy base."},
{w: "baseball", p: "n.", t: "棒球", s: "He likes to play baseball."},
{w: "bath", p: "n. v.", t: "洗澡", s: "Take a bath every day."},
{w: "bathe", p: "v.", t: "沐浴;浸濕", s: "Don't forget to bathe the dog."},
{w: "be", p: "v.", t: "是", s: "I want to be a teacher."},
{w: "beauty", p: "n.", t: "美貌;美人", s: "She is a famous beauty."},
{w: "become", p: "v.", t: "變成", s: "The weather became very cold."},
{w: "begin", p: "v.", t: "開始", s: "Class begins at eight o'clock."},
{w: "beginner", p: "n.", t: "初學者", s: "This class is for beginners."},
{w: "believe", p: "v.", t: "相信", s: "I believe you can do it."},
{w: "belong", p: "v.", t: "屬於", s: "This book belongs to me."},
{w: "besides", p: "prep. adv.", t: "而且;除...之外", s: "What do you like besides music?"},
{w: "beyond", p: "prep. adv. n.", t: "超過;超脫於", s: "The beauty of the mountain is beyond words."},
{w: "biology", p: "n.", t: "生物學", s: "We study plants in biology class."},
{w: "bite", p: "v. n.", t: "咬", s: "Don't let the dog bite you."},
{w: "blame", p: "v. n.", t: "責備", s: "Don't blame others for your mistake."},
{w: "block", p: "n. v.", t: "街區;阻擋", s: "Walk down two blocks and turn left."},
{w: "blood", p: "n. v.", t: "血液", s: "His blood type is O."},
{w: "bookstore", p: "n.", t: "書店", s: "Let's go to the bookstore."},
{w: "bored", p: "adj.", t: "感到無聊的", s: "I am bored with this movie."},
{w: "boring", p: "adj.", t: "令人無聊的", s: "The movie is very boring."},
{w: "bother", p: "v. n.", t: "打擾", s: "Sorry to bother you."},
{w: "bottom", p: "n. adj. v.", t: "底部", s: "There is some water at the bottom."},
{w: "break", p: "v. n.", t: "打破;休息", s: "Let's take a 10-minute break."},
{w: "bring", p: "v.", t: "帶", s: "Bring your umbrella with you."},
{w: "build", p: "v. n.", t: "建造", s: "They are building a new house."},
{w: "buy", p: "v. n.", t: "買", s: "I want to buy a new bag."},
{w: "camp", p: "v. n.", t: "露營", s: "We camped by the river."},
{w: "careful", p: "adj.", t: "小心的", s: "Be careful when you cross the road."},
{w: "case", p: "n. v.", t: "情形；盒；箱", s: "In this case, we should stay home."},
{w: "cause", p: "v. n.", t: "引起，造成", s: "The heavy rain caused the flood."},
{w: "celebrate", p: "v.", t: "慶祝", s: "Let's celebrate your birthday."},
{w: "cell phone", p: "n.", t: "手機", s: "I forgot to bring my cell phone."},
{w: "cent", p: "n.", t: "分(錢幣)", s: "A dollar is one hundred cents."}
],
"Flyer-A": [
{w: "center", p: "n.", t: "中心", s: "The park is in the center of the city."},
{w: "century", p: "n.", t: "世紀", s: "We are living in the 21st century."},
{w: "certain", p: "adj.", t: "確定的", s: "I am certain that he will come."},
{w: "chance", p: "n.", t: "機會", s: "Give me one more chance, please."},
{w: "chart", p: "n.", t: "圖表", s: "Look at the weather chart."},
{w: "cheat", p: "v.", t: "作弊;欺騙", s: "Don't cheat on the English test."},
{w: "cheer", p: "v. n.", t: "歡呼", s: "The fans cheered for the team."},
{w: "chemistry", p: "n.", t: "化學", s: "We study molecules in chemistry class."},
{w: "childhood", p: "n.", t: "童年", s: "I had a happy childhood."},
{w: "choice", p: "n.", t: "選擇", s: "You have no other choice."},
{w: "Christmas", p: "n.", t: "聖誕節", s: "We get presents on Christmas."},
{w: "church", p: "n.", t: "教堂", s: "My family goes to church on Sunday."},
{w: "climb", p: "v.", t: "爬", s: "Don't climb the tree. It's dangerous."},
{w: "coast", p: "n.", t: "海岸", s: "We drove along the coast."},
{w: "collect", p: "v.", t: "收集", s: "He likes to collect stamps."},
{w: "color", p: "n. v.", t: "顏色", s: "What is your favorite color?"},
{w: "colorful", p: "adj.", t: "多采多姿;色彩鮮豔", s: "The garden is full of colorful flowers."},
{w: "comfortable", p: "adj.", t: "舒服的", s: "This sofa is very comfortable."},
{w: "comic", p: "n. adj.", t: "漫畫(的)", s: "I like to read comic books."},
{w: "common", p: "adj.", t: "普通的;常見的", s: "Dogs are common pets."},
{w: "computer", p: "n.", t: "電腦", s: "I play games on the computer."},
{w: "concern", p: "v. n.", t: "關心", s: "The health of the earth concerns us all."},
{w: "considerate", p: "adj.", t: "體貼的", s: "He is a very considerate boy."},
{w: "convenient", p: "adj.", t: "便利的", s: "The supermarket is very convenient."},
{w: "cookie", p: "n.", t: "餅乾", s: "Would you like a chocolate cookie?"},
{w: "corner", p: "n.", t: "轉角;角落", s: "The shop is at the corner of the street."},
{w: "correct", p: "adj. v.", t: "正確的", s: "Your answer is correct."},
{w: "couch", p: "n.", t: "沙發", s: "Dad is sleeping on the couch."},
{w: "cousin", p: "n.", t: "堂(表)兄弟姊妹", s: "My cousin lives in Taipei."},
{w: "crayon", p: "n.", t: "蠟筆", s: "I draw a rainbow with crayons."},
{w: "crazy", p: "adj.", t: "瘋狂的", s: "Are you crazy? It's too cold out!"},
{w: "current", p: "adj. n.", t: "現在的;水流", s: "What is your current address?"},
{w: "cute", p: "adj.", t: "可愛的", s: "The baby is very cute."},
{w: "dawn", p: "n.", t: "黎明", s: "The sun rises at dawn."},
{w: "decrease", p: "v. n.", t: "減少", s: "The population began to decrease."},
{w: "department store", p: "n.", t: "百貨公司", s: "Let's go shopping at the department store."},
{w: "describe", p: "v.", t: "形容;描述", s: "Can you describe the man?"},
{w: "develop", p: "v.", t: "發展", s: "The city is developing fast."},
{w: "diet", p: "n. v.", t: "節食;飲食", s: "I'm on a diet to lose weight."},
{w: "dig", p: "v. n.", t: "挖", s: "The dog is digging a hole."},
{w: "dinosaur", p: "n.", t: "恐龍", s: "Dinosaurs lived a long time ago."},
{w: "diplomat", p: "n.", t: "外交官", s: "A diplomat works for his country."},
{w: "discuss", p: "v.", t: "討論", s: "Let's discuss the problem together."},
{w: "dish", p: "n.", t: "盤子", s: "Wash the dishes after dinner."},
{w: "distant", p: "adj.", t: "遠離的", s: "The stars are very distant."},
{w: "divide", p: "v.", t: "分割;除以", s: "Divide the cake into four pieces."},
{w: "do", p: "v.", t: "做", s: "Do your homework now."},
{w: "doll", p: "n.", t: "洋娃娃", s: "The girl is playing with her doll."},
{w: "dozen", p: "n.", t: "(一)打", s: "I bought a dozen eggs."},
{w: "Dr.", p: "n.", t: "博士;醫師", s: "Dr. Lin is a famous scientist."},
{w: "dream", p: "n. v.", t: "作夢；夢想", s: "I had a strange dream last night."},
{w: "drop", p: "v. n.", t: "掉落", s: "Don't drop the glass bottle."},
{w: "duty", p: "n.", t: "職責", s: "It is my duty to help you."},
{w: "eagle", p: "n.", t: "老鷹", s: "The eagle is flying high."},
{w: "edge", p: "n.", t: "邊緣", s: "Don't stand near the edge."},
{w: "education", p: "n.", t: "教育", s: "Education is very important."},
{w: "effort", p: "n.", t: "努力", s: "You should put more effort into it."},
{w: "electric", p: "adj.", t: "電的", s: "We have an electric car."},
{w: "elementary school", p: "n.", t: "小學", s: "I go to an elementary school."},
{w: "else", p: "adv.", t: "其他", s: "What else do you want?"},
{w: "embarrass", p: "v.", t: "使 ~ 難堪", s: "I didn't mean to embarrass you."},
{w: "empty", p: "adj. v.", t: "空的", s: "The bottle is empty."},
{w: "energetic", p: "adj.", t: "活力充沛", s: "He is an energetic boy."},
{w: "enter", p: "v.", t: "進入", s: "Enter the room quietly."},
{w: "envy", p: "v. n.", t: "羨慕", s: "I envy your good luck."},
{w: "equal", p: "adj. v. n.", t: "相等;等於", s: "Two plus two equals four."},
{w: "eve", p: "n.", t: "前夕", s: "We have a party on New Year's Eve."},
{w: "everyone", p: "pron.", t: "每一人", s: "Everyone is happy today."},
{w: "example", p: "n.", t: "例子", s: "Give me an example, please."},
{w: "excited", p: "adj.", t: "興奮的", s: "I'm excited about the trip."},
{w: "experience", p: "n. v.", t: "經驗", s: "He has much experience in teaching."},
{w: "fall", p: "v. n.", t: "掉落;秋天", s: "The leaves fall in autumn."},
{w: "fancy", p: "adj. n. v.", t: "幻想;想像的;華麗的", s: "They stayed in a fancy hotel."},
{w: "fantastic", p: "adj.", t: "很棒的", s: "You did a fantastic job!"},
{w: "fashionable", p: "adj.", t: "時髦的", s: "She is wearing a fashionable hat."},
{w: "fast", p: "adj. adv.", t: "快速的", s: "He runs very fast."},
{w: "fat", p: "adj. n.", t: "肥的", s: "The cat is too fat."},
{w: "favorite", p: "adj. n.", t: "最愛的", s: "Blue is my favorite color."},
{w: "feed", p: "v. n.", t: "餵;飼養", s: "Don't forget to feed the dog."},
{w: "feel", p: "v. n.", t: "感覺", s: "I feel great today."},
{w: "female", p: "n. adj.", t: "女性", s: "The bird is a female."},
{w: "festival", p: "n.", t: "慶典", s: "The Moon Festival is coming."},
{w: "finally", p: "adv.", t: "最後地", s: "Finally, we arrived home."},
{w: "find", p: "v. n.", t: "找到", s: "I can't find my keys."},
{w: "finger", p: "n. v.", t: "指頭", s: "I have ten fingers."},
{w: "finish", p: "v. n.", t: "結束", s: "I finished my homework."},
{w: "fix", p: "v. n.", t: "修理", s: "Can you fix my bike?"},
{w: "flag", p: "n. v.", t: "旗子", s: "The national flag is flying."},
{w: "foot", p: "n.", t: "腳", s: "I go to school on foot."},
{w: "foreigner", p: "n.", t: "外國人", s: "The foreigner is from America."},
{w: "forget", p: "v.", t: "忘記", s: "Don't forget to close the door."},
{w: "formal", p: "adj.", t: "正式的", s: "He wore a formal suit to the party."},
{w: "forward", p: "adv. adj. n. v.", t: "向前的;向前地", s: "Take one step forward."},
{w: "friendship", p: "n.", t: "友誼", s: "Our friendship is very important."},
{w: "fry", p: "v. n.", t: "炒;煎", s: "I like to eat fried chicken."},
{w: "furniture", p: "n.", t: "家俱", s: "They bought some new furniture."},
{w: "garbage", p: "n.", t: "垃圾", s: "Please take out the garbage."},
{w: "gas", p: "n. v.", t: "瓦斯;氣體;汽油", s: "The car is out of gas."},
{w: "gather", p: "v. n.", t: "團聚;聚集", s: "The family gathered for dinner."},
{w: "general", p: "adj. n.", t: "普遍的;一般的", s: "That is a general rule."},
{w: "genius", p: "n.", t: "天才", s: "Einstein was a genius."},
{w: "get", p: "v.", t: "變成;得到", s: "It's getting cold."},
{w: "giant", p: "n. adj.", t: "巨人", s: "The giant is very tall."},
{w: "gift", p: "n.", t: "禮物", s: "A birthday gift for you."},
{w: "gram", p: "n.", t: "公克", s: "One thousand grams is a kilogram."},
{w: "grow", p: "v.", t: "生長", s: "Plants grow in the sun."},
{w: "guess", p: "v. n.", t: "猜", s: "Can you guess my age?"},
{w: "habit", p: "n.", t: "習慣", s: "Good habits are important."},
{w: "haircut", p: "n.", t: "理頭髮", s: "I need a haircut."},
{w: "handsome", p: "adj.", t: "英俊的", s: "The actor is very handsome."},
{w: "hang", p: "v. n.", t: "掛;吊", s: "Hang your coat on the hook."},
{w: "hard-working", p: "adj.", t: "認真工作的", s: "He is a hard-working student."},
{w: "have (has, had)", p: "v. aux.", t: "擁有;已經", s: "I have a new book."},
{w: "headache", p: "n.", t: "頭痛", s: "I have a terrible headache."},
{w: "health", p: "n.", t: "健康", s: "Health is better than wealth."},
{w: "hear", p: "v.", t: "聽見", s: "Can you hear the music?"},
{w: "heat", p: "n. v.", t: "熱", s: "The heat of the sun."},
{w: "helpful", p: "adj.", t: "有益的;有幫助的", s: "The book is very helpful."},
{w: "hide", p: "v. n.", t: "藏匿;躲藏", s: "Hide-and-seek is fun."},
{w: "hit", p: "v. n.", t: "打;擊中", s: "He hit the ball hard."},
{w: "hobby", p: "n.", t: "嗜好", s: "What is your hobby?"},
{w: "hold", p: "v. n.", t: "拿;握;舉行", s: "Hold my hand, please."},
{w: "honest", p: "adj.", t: "誠實的", s: "An honest person doesn't lie."},
{w: "however", p: "adv. conj.", t: "無論如何;然而", s: "However, I don't agree."},
{w: "hurt", p: "v. n. adj.", t: "傷害;疼痛", s: "My leg hurts."},
{w: "ignore", p: "v.", t: "忽略;疏忽", s: "Don't ignore the rules."},
{w: "importance", p: "n.", t: "重要", s: "I know the importance of health."},
{w: "income", p: "n.", t: "收入", s: "His income is very high."},
{w: "increase", p: "v. n.", t: "增加", s: "The price began to increase."},
{w: "indicate", p: "v.", t: "指示;指出", s: "The map indicates the way."},
{w: "information", p: "n.", t: "資訊;訊息", s: "I need some information."},
{w: "insist", p: "v.", t: "堅持", s: "He insists on going."},
{w: "interest", p: "n. v.", t: "興趣", s: "I have no interest in music."},
{w: "interested", p: "adj.", t: "感到興趣的", s: "I am interested in art."},
{w: "interesting", p: "adj.", t: "有趣的", s: "The story is very interesting."},
{w: "jeans", p: "n.", t: "牛仔褲", s: "I like wearing jeans."},
{w: "job", p: "n.", t: "職業、工作", s: "He has a good job."},
{w: "jog", p: "v. n.", t: "慢跑", s: "I jog every morning."},
{w: "joy", p: "n. v.", t: "喜悅", s: "The baby brings us joy."},
{w: "junior high school", p: "n.", t: "國中", s: "He is in junior high school."},
{w: "kick", p: "v. n.", t: "踢", s: "Don't kick the chair."},
{w: "kid", p: "n. v.", t: "小孩", s: "The kids are playing."},
{w: "kill", p: "v. n.", t: "殺", s: "Don't kill the spider."},
{w: "kilometer", p: "n.", t: "公里", s: "Ten kilometers."},
{w: "king", p: "n.", t: "國王", s: "The king lives in a castle."},
{w: "kite", p: "n.", t: "風箏", s: "Let's fly a kite."},
{w: "knee", p: "n. v.", t: "膝蓋", s: "He hurt his knee."},
{w: "know", p: "v. n.", t: "知道", s: "I know the answer."},
{w: "knowledge", p: "n.", t: "知識", s: "Knowledge is power."},
{w: "latest", p: "adj. adv.", t: "最近的;最新", s: "The latest news."},
{w: "latter", p: "adj. n.", t: "後半的;後者", s: "The latter part of the book."},
{w: "lead", p: "v. n.", t: "帶領", s: "Lead us to the way."},
{w: "leader", p: "n.", t: "領導者", s: "He is a good leader."},
{w: "least", p: "adj. adv. n.", t: "最少", s: "At least we tried."},
{w: "leave", p: "v. n.", t: "離開", s: "Don't leave me alone."},
{w: "lemon", p: "n.", t: "檸檬", s: "The lemon is sour."},
{w: "less", p: "adj. adv. pron. n.", t: "較少的", s: "Less than ten."},
{w: "level", p: "n. adj. v.", t: "程度;水準", s: "What's your English level?"},
{w: "lick", p: "v. n.", t: "舔", s: "The dog licked my hand."},
{w: "likely", p: "adj. adv.", t: "好像;可能的", s: "It is likely to rain."},
{w: "lip", p: "n.", t: "嘴唇", s: "Her lips are red."},
{w: "liter", p: "n.", t: "公升", s: "One liter of milk."},
{w: "lonely", p: "adj.", t: "寂寞的", s: "I feel lonely."},
{w: "lose", p: "v.", t: "失去", s: "Don't lose your way."},
{w: "lucky", p: "adj.", t: "幸運的", s: "Lucky you!"},
{w: "magic", p: "n. adj.", t: "神奇的;魔術", s: "A magic show."},
{w: "mail", p: "n. v.", t: "郵件", s: "Did I get any mail?"},
{w: "mailman(mail carrier)", p: "n.", t: "郵差", s: "The mailman is coming."},
{w: "major", p: "adj. n. v.", t: "主要的", s: "A major problem."},
{w: "man", p: "n.", t: "男人", s: "He is a tall man."},
{w: "mark", p: "v. n.", t: "做上記號;分數", s: "Mark the answer."},
{w: "married", p: "adj.", t: "結婚的", s: "They are married."},
{w: "marvelous", p: "adj.", t: "了不起;絕妙的", s: "The food is marvelous."},
{w: "master", p: "n. v.", t: "主人;大師", s: "He is a master of art."},
{w: "match", p: "v. n.", t: "搭配;火柴;比賽", s: "The tie matches the shirt."},
{w: "math", p: "n.", t: "數學", s: "Math is fun."},
{w: "mean", p: "v. adj. n.", t: "意指;卑鄙的", s: "What does it mean?"},
{w: "media", p: "n.", t: "媒體", s: "Social media."},
{w: "medium", p: "adj. n.", t: "中間;中等", s: "A medium size."},
{w: "menu", p: "n.", t: "菜單", s: "Look at the menu."}
],
"Flyer-B": [
{w: "mile", p: "n.", t: "英哩", s: "The park is about one mile from here."},
{w: "more", p: "adj. adv.", t: "更多", s: "I need some more time to finish it."},
{w: "motorcycle", p: "n.", t: "機車", s: "My uncle rides a motorcycle to work."},
{w: "Mr.", p: "n.", t: "先生", s: "Mr. Lin is our new neighbor."},
{w: "Mrs.", p: "n.", t: "太太", s: "Mrs. White is a very kind lady."},
{w: "Ms.", p: "n.", t: "小姐或太太", s: "Ms. Chen is our English teacher."},
{w: "national", p: "adj.", t: "國家的", s: "The national flag is flying in the wind."},
{w: "neck", p: "n.", t: "脖子", s: "The giraffe has a very long neck."},
{w: "next", p: "adj. adv.", t: "下一個", s: "Next time, please be more careful."},
{w: "nod", p: "v. n.", t: "點頭", s: "He nodded to say yes."},
{w: "notice", p: "v. n.", t: "注意", s: "Did you notice the sign on the wall?"},
{w: "novel", p: "n. adj.", t: "小說", s: "I am reading an interesting novel."},
{w: "officer", p: "n.", t: "官員;警官", s: "The police officer helped the old man."},
{w: "oil", p: "n.", t: "油", s: "Mom uses olive oil for cooking."},
{w: "oneself", p: "pron.", t: "~自己", s: "One should take care of oneself."},
{w: "order", p: "v. n.", t: "點餐;命令", s: "Are you ready to order your meal?"},
{w: "pack", p: "n. v.", t: "一包;打包", s: "A pack of cards; pack your bags."},
{w: "package", p: "n. v.", t: "包裹", s: "The postman delivered a package to me."},
{w: "paint", p: "v. n.", t: "油漆;繪畫", s: "We are going to paint the wall white."},
{w: "part", p: "n. v.", t: "部分", s: "This is the best part of the movie."},
{w: "PE", p: "n.", t: "體育", s: "We play basketball in PE class."},
{w: "pet", p: "n. v.", t: "寵物", s: "Do you have any pets at home?"},
{w: "physics", p: "n.", t: "物理學", s: "Physics is a difficult subject for me."},
{w: "planet", p: "n.", t: "行星", s: "Mars is called the Red Planet."},
{w: "player", p: "n.", t: "球員;選手", s: "He is a famous basketball player."},
{w: "pocket", p: "n. v. adj.", t: "口袋", s: "I put the keys in my pocket."},
{w: "point", p: "n. v.", t: "觀點;點", s: "That is a very good point."},
{w: "pork", p: "n.", t: "豬肉", s: "My sister doesn't like to eat pork."},
{w: "post office", p: "n.", t: "郵局", s: "I need to go to the post office."},
{w: "postcard", p: "n.", t: "明信片", s: "Send me a postcard from Taipei."},
{w: "powder", p: "n. v.", t: "粉末", s: "The ground was covered with white powder."},
{w: "prepare", p: "v.", t: "準備", s: "Mom is preparing dinner in the kitchen."},
{w: "present", p: "n. adj. v.", t: "禮物;出席", s: "Everyone was present at the meeting."},
{w: "price", p: "n. v.", t: "價錢", s: "The price of the toy is too high."},
{w: "professor", p: "n.", t: "教授", s: "My uncle is a history professor."},
{w: "program", p: "n. v.", t: "節目;計畫", s: "What is your favorite TV program?"},
{w: "proud", p: "adj.", t: "驕傲的;自豪的", s: "My parents are proud of me."},
{w: "public", p: "adj. n.", t: "公共的", s: "Don't shout in public places."},
{w: "queen", p: "n.", t: "皇后", s: "The queen lives in a beautiful castle."},
{w: "recorder", p: "n.", t: "錄音機", s: "I use a voice recorder to learn English."},
{w: "recycle", p: "v. n.", t: "回收", s: "We should recycle paper and bottles."},
{w: "refrigerator", p: "n.", t: "冰箱", s: "Put the milk in the refrigerator."},
{w: "regular", p: "adj. n.", t: "有規則的;定期的", s: "He has regular exercise every day."},
{w: "repeat", p: "v. n.", t: "重複", s: "Please repeat what you said."},
{w: "report", p: "n. v.", t: "報告", s: "I have to finish my science report."},
{w: "reporter", p: "n.", t: "記者", s: "A reporter is interviewing the singer."},
{w: "result", p: "n. v.", t: "結果", s: "The result of the test was good."},
{w: "ROC", p: "n.", t: "中華民國", s: "ROC stands for Republic of China."},
{w: "role", p: "n.", t: "角色", s: "She played a leading role in the play."},
{w: "Roller-blade", p: "v. n.", t: "溜直排輪", s: "I like to Roller-blade in the park."},
{w: "root", p: "n. v.", t: "根", s: "The roots of the tree go deep."},
{w: "rule", p: "n. v.", t: "規則", s: "We must follow the school rules."},
{w: "safe", p: "adj. n.", t: "安全的", s: "It is safe to cross the street here."},
{w: "sale", p: "n.", t: "廉售;拍賣", s: "The shoes are on sale this week."},
{w: "scene", p: "n.", t: "風景;舞台;場景", s: "The opening scene of the movie."},
{w: "scenery", p: "n.", t: "景色", s: "The mountain scenery is very beautiful."},
{w: "scooter", p: "n.", t: "滑板車;輕型機車", s: "He rides a scooter to school."},
{w: "seldom", p: "adv.", t: "很少", s: "It seldom rains in the desert."},
{w: "sell", p: "v.", t: "賣", s: "They sell fresh bread here."},
{w: "senior high school", p: "n.", t: "高中", s: "My brother is in senior high school."},
{w: "sense", p: "n. v.", t: "感覺;意義", s: "A sense of humor is important."},
{w: "sentence", p: "n. v.", t: "句子", s: "Can you make a sentence with this word?"},
{w: "shall", p: "modal v.", t: "將要", s: "Shall we go for a walk?"},
{w: "shape", p: "n. v.", t: "形狀", s: "The cookie is in the shape of a star."},
{w: "share", p: "v. n.", t: "分享", s: "Let's share the cake together."},
{w: "she", p: "pron.", t: "她", s: "She is the best student in our class."},
{w: "shoot", p: "v. n.", t: "射擊", s: "Don't shoot the birds."},
{w: "shop", p: "n. v.", t: "商店", s: "The flower shop is closed today."},
{w: "shopkeeper", p: "n.", t: "店主", s: "The shopkeeper is very friendly."},
{w: "should", p: "aux. modal v.", t: "應該", s: "You should study hard for the test."},
{w: "shoulder", p: "n. v.", t: "肩膀", s: "He carried the bag on his shoulder."},
{w: "sidewalk", p: "n.", t: "人行道", s: "Walk on the sidewalk for safety."},
{w: "sight", p: "n. v.", t: "景象;視力", s: "His sight is getting better."},
{w: "simple", p: "adj.", t: "簡單的", s: "This is a simple math problem."},
{w: "skate", p: "v. n.", t: "溜冰", s: "I like to skate on the ice."},
{w: "skillful", p: "adj.", t: "熟練的", s: "He is a skillful piano player."},
{w: "sleepy", p: "adj.", t: "想睡的", s: "I feel very sleepy after lunch."},
{w: "smart", p: "adj.", t: "聰明的", s: "You are a very smart student."},
{w: "smell", p: "v. n.", t: "聞到;聞起來", s: "The flowers smell wonderful."},
{w: "smoke", p: "v. n.", t: "抽煙;冒煙", s: "Smoking is bad for your health."},
{w: "snack", p: "n. v.", t: "點心", s: "I always have a snack after school."},
{w: "someone", p: "pron.", t: "一些人;某人", s: "Someone is knocking at the door."},
{w: "sometimes", p: "adv.", t: "有時候", s: "Sometimes I go to the library."},
{w: "somewhere", p: "adv. pron.", t: "某處", s: "I have seen him somewhere before."},
{w: "soul", p: "n.", t: "靈魂", s: "Music is good for the soul."},
{w: "sound", p: "v. n. adj.", t: "聽起來;聲音", s: "That sounds like a great plan."},
{w: "special", p: "adj. n.", t: "特別的", s: "Today is a very special day."},
{w: "spend", p: "v. n.", t: "花費(時間/金錢)", s: "Don't spend too much money."},
{w: "state", p: "n. v. adj.", t: "州;狀態", s: "New York is a large state."},
{w: "stationery", p: "n.", t: "文具", s: "I bought some pens at the stationery store."},
{w: "steak", p: "n.", t: "牛排", s: "I'd like my steak medium, please."},
{w: "stomach", p: "n. v.", t: "胃;肚子", s: "My stomach hurts."},
{w: "stone", p: "n. v.", t: "石頭", s: "The boy threw a stone into the river."},
{w: "store", p: "n. v.", t: "商店;儲存", s: "The grocery store is open now."},
{w: "strange", p: "adj. adv.", t: "奇怪的", s: "I heard a strange noise last night."},
{w: "stranger", p: "n.", t: "陌生人", s: "Don't talk to strangers."},
{w: "stupid", p: "adj.", t: "愚笨的", s: "I made a stupid mistake."},
{w: "subject", p: "n. adj. v.", t: "學科;主詞", s: "Math is my favorite subject."},
{w: "successful", p: "adj.", t: "成功的", s: "He is a successful businessman."},
{w: "suggest", p: "v.", t: "建議", s: "I suggest that we go home now."},
{w: "surf", p: "v. n.", t: "上網;衝浪", s: "I like to surf the Internet."},
{w: "surprise", p: "v. n.", t: "驚訝;使驚奇", s: "What a big surprise!"},
{w: "surprised", p: "adj.", t: "感到驚訝的", s: "I was surprised by the news."},
{w: "system", p: "n.", t: "系統", s: "The computer system is down."},
{w: "Taiwan", p: "n.", t: "台灣", s: "Taiwan is a beautiful island."},
{w: "talent", p: "n.", t: "天分", s: "She has a talent for music."},
{w: "tape", p: "n. v.", t: "錄音帶;膠帶", s: "Use tape to fix the paper."},
{w: "taste", p: "v. n.", t: "嚐起來;品味", s: "The cake tastes very sweet."},
{w: "teenager", p: "n.", t: "青少年", s: "Teenagers like to play video games."},
{w: "tennis", p: "n.", t: "網球", s: "Let's play tennis after school."},
{w: "terrific", p: "adj.", t: "好極了", s: "You did a terrific job!"},
{w: "than", p: "conj. prep.", t: "比", s: "He is taller than me."},
{w: "theater", p: "n.", t: "戲院", s: "Let's go to the movie theater."},
{w: "then", p: "adv. n. adj.", t: "那時;然後", s: "First wash hands, then eat."},
{w: "therefore", p: "adv.", t: "因此", s: "It rained; therefore, we stayed home."},
{w: "thirsty", p: "adj.", t: "口渴的", s: "I am very thirsty."},
{w: "though", p: "conj. adv.", t: "雖然", s: "Though it was raining, he went out."},
{w: "tip", p: "n. v.", t: "訣竅;小費", s: "Here is a useful tip for you."},
{w: "tired", p: "adj.", t: "疲累的", s: "I am tired after the long walk."},
{w: "together", p: "adv.", t: "一起", s: "Let's sing together."},
{w: "tooth", p: "n.", t: "牙齒", s: "I have a toothache."},
{w: "touch", p: "v. n.", t: "接觸;碰到", s: "Don't touch the wet paint."},
{w: "towel", p: "n.", t: "毛巾", s: "Dry your hands with a towel."},
{w: "toy", p: "n. v.", t: "玩具", s: "The child is playing with a toy."},
{w: "traffic", p: "n. v.", t: "交通", s: "The traffic is heavy today."},
{w: "trick", p: "n. v.", t: "把戲;策略;秘訣", s: "The magician showed us a trick."},
{w: "trip", p: "n. v.", t: "旅行", s: "Have a nice trip to Taipei."},
{w: "true", p: "adj. adv. n. v.", t: "真實的", s: "Is the story true or false?"},
{w: "twice", p: "adv.", t: "兩次", s: "I brush my teeth twice a day."},
{w: "umbrella", p: "n.", t: "雨傘", s: "Don't forget your umbrella."},
{w: "understand", p: "v.", t: "了解", s: "I don't understand this word."},
{w: "unhappy", p: "adj.", t: "不高興的", s: "She looks very unhappy today."},
{w: "university", p: "n.", t: "大學", s: "He wants to go to a top university."},
{w: "upper", p: "adj. n.", t: "上;較高的", s: "The upper floor of the building."},
{w: "USA", p: "n.", t: "美國", s: "USA stands for United States of America."},
{w: "vacation", p: "n. v.", t: "假期", s: "We are going on vacation next week."},
{w: "Valentine", p: "n.", t: "情人節", s: "Happy Valentine's Day!"},
{w: "vendor", p: "n.", t: "攤販", s: "There are many food vendors here."},
{w: "voice", p: "n. v.", t: "聲音", s: "She has a beautiful voice."},
{w: "waiter", p: "n. v.", t: "服務生", s: "The waiter brought us the menu."},
{w: "waitress", p: "n. v.", t: "女服務生", s: "The waitress is very helpful."},
{w: "wake", p: "v. n.", t: "喚醒;醒來", s: "Wake me up at seven o'clock."},
{w: "waterfall", p: "n.", t: "瀑布", s: "The waterfall is very tall."},
{w: "weekday", p: "n. adj.", t: "工作日", s: "I am busy on weekdays."},
{w: "weekend", p: "n. v.", t: "週末", s: "Have a nice weekend!"},
{w: "wild", p: "adj. adv. n.", t: "野生的", s: "Wild animals live in the forest."},
{w: "win", p: "v. n.", t: "贏", s: "We want to win the game."},
{w: "wise", p: "adj.", t: "有智慧的", s: "He is a wise old man."},
{w: "with", p: "prep.", t: "與;用", s: "Go to school with your friends."},
{w: "workbook", p: "n.", t: "作業本", s: "Open your workbook to page five."},
{w: "write", p: "v.", t: "寫", s: "Write your name here, please."}
]
};